### ISSUE TITLE
KEDA Implementation ways

### ISSUE THREAD

**Issue by pavan-chakka** [kedacore/keda#2993] opened 2022-05-03 23:24 UTC
Hello,

In our org, we use Azure as our cloud services, and we have several teams who work on various applications/Azure functions. In Azure, we have non prod AKS cluster and Prod AKS cluster. We run our applications dev, test, QA APPs on non prod AKS cluster and prod on Prod AKS cluster. Each AKS cluster have namespace allocated for each team and they run their apps in PODS in their allocated namespaces. A team member will have access only to their name space and not to other team namespace.

Several of our teams have Batch jobs and functions which need to be triggered with an Event occurrence. So, we want to use KEDA to scale based on volume of events. We want to see if it is doable to have KEDA in each name space of an AKS cluster and deploy their functions/batch jobs in their name space and scale them based on events.

Our understanding is that we can have only one KEDA installed per AKS cluster. If this is true, how many functions KEDA can handle per AKS cluster, and how can we organize Azure functions/APPS/Batch processes per team/ per project.

If we can have multiple KEDAs per AKS (preferably one KEDA per name space), then how to implement this.

Please advise on best architecting ways around KEDA, and how other organizations are implementing it. Thanks.

**Comment by tomkerkhove** [comment] 2022-05-04 07:04
Duplicate of https://github.com/kedacore/keda/discussions/2994

**Closed by tomkerkhove** 2022-05-04 07:04 UTC
