### ISSUE TITLE
HTTP Keda with prometheus implemented api is scaling even though there is no load sent to it.

### ISSUE THREAD

**Issue by KasyapG** [kedacore/keda#5176] opened 2023-11-10 08:55 UTC
### Discussed in https://github.com/kedacore/keda/discussions/5172

<div type='discussions-op-text'>

<sup>Originally posted by **KasyapG** November  9, 2023</sup>
We have implemented HTTP Keda with promethues.

Implemented the scaledobject on a test api, the scaling is working perfectly whenever there is load coming to the api.

However I have noticed that whenever there is load on other api as well this test api strts spinning up pods to scale.

Steps Implemented:

- Keda setup complete (version 2.9.0)
- Deployed prometheus from https://github.com/kubernetes/ingress-nginx/tree/main/deploy/prometheus using kustomize command.
- Applied below scalaed object to test api to scale whenever there is certain threshold of requests coming to ingress sum(rate(nginx_ingress_controller_requests[1m]))

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: prometheus-scaledobject-test-sample-kg
  namespace: 60436a51-7059-4f45-b1be-a0069c86b864
  labels:
    deploymentName: test-sample-kg
spec:
  scaleTargetRef:
    name: test-sample-kg
  pollingInterval: 15
  cooldownPeriod:  30
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-server.ingress-nginx.svc.cluster.local:9090
        metricName: access_frequency
        threshold: '1'
        query: sum(rate(nginx_ingress_controller_requests[1m]))
		
- I tried making api specific but on this query was working.

Issue : WHenever there is load coming to other api, this test api also starts spinning the pods as the ingre_controller requests has crossed the threshold.

Could you please suggest if ther any othe query I can use to make it api specific.

Also correct if my understanding is incorrect.</div>

**Comment by tomkerkhove** [comment] 2023-11-13 08:04
Duplicate of https://github.com/kedacore/keda/discussions/5172

**Closed by tomkerkhove** 2023-11-13 08:04 UTC
