### ISSUE TITLE
Keda Not able to Scale job based on Azure queue message 

### ISSUE THREAD

**Issue by sachinagarwal010** [kedacore/keda#3341] opened 2022-07-08 10:48 UTC
### Report

We have Azure Storage Queue having few messages there and Keda is creating the scaled Job based on Azure queue message available (Auto Scaling max Replica Set was set to 30) but when we already have scaled 30 jobs and those jobs are finished then keda started picking the azure queue messages 1 by 1 not based on the Auto Scaling max Replica Set was set to 30.

### Expected Behavior

Keda should create the scaled jobs based on the auto replica count setting.

### Actual Behavior

Keda is creating jobs sequentially.

### Steps to Reproduce the Problem

1.
2.
3.

### Logs from KEDA operator

```
example
```

### KEDA Version

2.7.1

### Kubernetes Version

1.23

### Platform

Microsoft Azure

**Comment by tomkerkhove** [comment] 2022-07-08 11:41
Duplicate of https://github.com/kedacore/keda/discussions/3340

**Closed by tomkerkhove** 2022-07-08 11:41 UTC
Labels: bug
