### ISSUE TITLE
Is "deploymentName" on ScaledObject really useful?

### ISSUE THREAD

**Issue by ppatierno** [kedacore/keda#631] opened 2020-02-16 08:18 UTC
I was wondering what is the rationale behind the decision to make the `deploymentName` label mandatory in the `ScaledObject` when there is the `spec.scaleTargetRef` as well.
As far as I can see the entire rest of the logic leverages on the `spec.scaleTargetRef`, why having the label as well?

**Comment by tomkerkhove** [comment] 2020-02-17 07:57
Duplicate of https://github.com/kedacore/keda/issues/545, let's keep the conversation going over there.

**Closed by tomkerkhove** 2020-02-17 07:57 UTC
