### ISSUE TITLE
Leaked connections in Prometheus scaler on query error

### ISSUE THREAD

**Issue by mycrEEpy** [kedacore/keda#5341] opened 2024-01-03 03:01 UTC
### Report

When (e.g. by mistake) using a query which returns multiple elements the connection to Prometheus seems to be leaking. This is not the case when using a query which (correctly) returns a single element. You can therefore bring down an entire Prometheus instance with connection starvation by simply using wrong queries in your KEDA scaler.

### Expected Behavior

Like with successful queries, the connections should not be leaking.

### Actual Behavior

The connections are being leaked, about 60 connections per ScaledObject (see screenshot).

![image](https://github.com/kedacore/keda/assets/6517708/dd159868-afbc-4ce9-90f1-fd5e4aeb0faf)

### Steps to Reproduce the Problem

1. Setup KEDA
2. Setup Prometheus with self scraping on localhost
3. Create Deployment with ScaledObject which uses a prometheus query which returns multiple elements, e.g. `rate(prometheus_http_requests_total[1m])`
4. Track the leaking connections with `net_conntrack_listener_conn_accepted_total{listener_name="http"} - net_conntrack_listener_conn_closed_total{listener_name="http"}`
5. Fix the query and see the connections drop: `sum(rate(prometheus_http_requests_total[1m]))`

![image](https://github.com/kedacore/keda/assets/6517708/22e65ed3-bb26-46d9-a043-e9d309cd6804)

### Logs from KEDA operator

```
2024-01-03T02:57:28Z    ERROR    scale_handler    error getting metric for scaler    {"scaledObject.Namespace": "default", "scaledObject.Name": "pause", "scaler": "prometheusScaler", "error": "prometheus query rate(prometheus_http_requests_total[1m]) returned multiple elements"}
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).GetScaledObjectMetrics
    /workspace/pkg/scaling/scale_handler.go:522
github.com/kedacore/keda/v2/pkg/metricsservice.(*GrpcServer).GetMetrics
    /workspace/pkg/metricsservice/server.go:47
github.com/kedacore/keda/v2/pkg/metricsservice/api._MetricsService_GetMetrics_Handler
    /workspace/pkg/metricsservice/api/metrics_grpc.pb.go:99
google.golang.org/grpc.(*Server).processUnaryRPC
    /workspace/vendor/google.golang.org/grpc/server.go:1343
google.golang.org/grpc.(*Server).handleStream
    /workspace/vendor/google.golang.org/grpc/server.go:1737
google.golang.org/grpc.(*Server).serveStreams.func1.1
    /workspace/vendor/google.golang.org/grpc/server.go:986
```

### KEDA Version

2.12.1

### Kubernetes Version

1.27

### Platform

Amazon Web Services

### Scaler Details

Prometheus

**Comment by JorTurFer** [comment] 2024-01-03 09:02
Hello @mycrEEpy 
Thanks for reporting! I think that this error has been already fixed with this PR: https://github.com/kedacore/keda/pull/5293
We will release a new version this month.
In the meantime, you can try it using `main` tag: ghcr.io/kedacore/keda:main (and feedback about if it's solved is more than welcomed)

**Comment by mycrEEpy** [comment] 2024-01-03 14:11
@JorTurFer I can confirm that on `main` the issue is fixed. If possible, please provide a patch release for it, as this caused production outages on our end.

**Comment by JorTurFer** [comment] 2024-01-03 14:32
Thanks for confirming that the issue is fixed!
We don't plan any patch release for v2.12, so you will have to wait until v2.13 for it (we will cut the release during this month) or use `main` tag (under your own risk as `main` isn't stable, if you go with this, I'd pin the docker sha instead of main).

I'm not 100% sure, but I'd say that disabling keep alive you can mitigate the issue too: https://keda.sh/docs/2.12/operate/cluster/#http-connection-disable-keep-alive

As this issue has been already fixed in main, I close it as solved

**Closed by JorTurFer** 2024-01-03 14:32 UTC
Labels: bug
