### ISSUE TITLE
Scaler requires Auth Trigger to be in the same namespace as ScaledObject

### ISSUE THREAD

**Issue by alexandery** [kedacore/keda#894] opened 2020-06-22 23:28 UTC
## Expected Behavior
Expect "authenticationRef" to be able to reference TriggerAuthentication object from another namespace using DNS naming of the service (see https://stackoverflow.com/a/44329470 for example)

## Actual Behavior
TriggerAuthentication  object is defined in 'default' namespace, while ScaledObject is defined in another namespace ('test'). Creating ScaledObject results in errors in keda-operator:

```
"level":"error","ts":1592866654.0380845,"logger":"scalehandler","msg":"Error getting triggerAuth","triggerAuthRef.Name":"keda-trigger-auth-kafka-credential","error":"TriggerAuthentication.keda.k8s.io \"keda-trigger-auth-kafka-credential\" not found".......
```

## Steps to Reproduce the Problem

  1. Create Secret and TriggerAuthentication  objects in 'default' namespace
  2. Create new namespace to hold ScaledObject 
  3. Create a ScaledObject  in the newly created namespace

## Specifications

  - **KEDA Version:** Latest installed Jun 22, 2020 via Helm
  - **Platform & Version:** Azure Kubernetes Service (AKS)
  - **Kubernetes Version:** v1.16.9
  - **Scaler(s):** Kafka

**Comment by tomkerkhove** [comment] 2020-06-23 08:25
I  think this is by design, right @zroubalik ?

**Comment by zroubalik** [comment] 2020-06-23 08:30
@tomkerkhove you are right (and I personally prefer the current desing).

**Comment by alexandery** [comment] 2020-06-23 14:03
May I ask for the arguments that make current design "better"?

k8s supports referencing object from different namespaces by using DNS notation, which provides flexibility. So in this regard Kafka scaler lacks in functionality compared to standard k8s. 

In my situation I need to support multiple namespaces which all need to reference the same auth details. Current Kafka scaler makes it impossible for me to do that cleanly - I have to create copies of the Secret and TriggerAuthentication objects in each namespace. In case when I need to update auth details I am forced into updating it multiple times making it error prone.

**Comment by alexandery** [comment] 2020-06-23 14:10
In addition, I just found another similar issue here #864 which @tomkerkhove seemed to support. The issue is pretty much the same as reported by me, except the solution proposed is not following k8s standard for referencing objects from other namespaces (not DNS notation, but separate 'namespace' parameter).

**Comment by tomkerkhove** [comment] 2020-06-24 14:51
I'm find with adding a field to configure it but definitely not the approach I'd use out-of-the-box!

**Comment by alexandery** [comment] 2020-06-24 15:23
@tomkerkhove Well, as long as the flexibility is there - it would be useful when such functionality is needed (like in my case). Whichever way this is supported is fine, I just figured it makes sense to use DNS notation to align it with other k8s functionality. Hopefully you guys can look into supporting this.

**Comment by tbickford** [comment] 2020-06-25 11:03
@alexandery Although I do understand your problem this seems to be more of antipattern. For example in standard Kubernetes design, pods do not have cross namespace access to secrets in other namespaces and this is with good reason of resource isolation.

**Comment by zroubalik** [comment] 2020-06-25 12:26
@alexandery sorry for the delay, I missed your last comments.  @tbickford explained my concerns really well.

I understand your problem and we can definitely discuss changes in this area if there's increased requests like this in community.

**Comment by erick-thompson** [comment] 2020-08-25 18:51
I was the person who opened 864. I think either dot or field for namespaces is fine. The reason I suggested the field is that it seemed to fit better with KEDA patterns, but the important part for me is the functionality, not the format.

**Comment by erick-thompson** [comment] 2020-08-25 19:07
> 
> 
> @alexandery Although I do understand your problem this seems to be more of antipattern. For example in standard Kubernetes design, pods do not have cross namespace access to secrets in other namespaces and this is with good reason of resource isolation.

I see your point about the anti-pattern, but I think it depends on your usage. 

For secrets/configmaps, the values are generally associated with a single application/service, so it makes sense to have them namespace scoped for both security and organization (don't need to worry about cross namespace permissions).

The scenario that I'm looking at is where we have a ton of triggered functions across a bunch of namespaces. The actual trigger mechanism is generally going to be one of a small set of services (e.g., one Azure storage account, one redis instances, etc). These shared services are intended to be a black box. So when a developer defines the ScaledObject and references the common TriggerAuthentication, they don't need to interact with Azure/AWS to define the permission (and deal with elevated permissions needed to make these changes). They simply define/create a new storage queue and can start using it right away.

There are a couple of reasons for this design. The first is that once developers start creating a TriggerAuthentication per function, we will end up with a ton of these scattered everywhere, and then maintaining/updating those secrets starts causing significant overhead. But a lot of it comes down to developer ergonomics.

**Comment by tomkerkhove** [comment] 2020-08-26 08:42
Hm I can see value in that indeed, certainly if you only want to have the auth defined somewhere.

However, I think it should be an opt-in if we start supporting it.

**Comment by adrianchifor** [comment] 2021-06-17 08:22
@tomkerkhove @zroubalik This is currently a blocker to us using auth with the Prometheue scaler, as Openshift operator cannot run without auth & tls and uses the Prometheus svc account token for auth. We can implement a workaround which replicates the svc account token to every namespace that needs metrics autoscaling but it feels very dirty and insecure.

This format makes a lot of sense https://github.com/kedacore/keda/issues/864#issuecomment-636957248

**Comment by coderanger** [comment] 2021-06-17 08:33
You can now use ClusterTriggerAuthentication objects for cross-ns credentials. I think we can probably close this?

**Comment by adrianchifor** [comment] 2021-06-17 09:24
Oh yea I just noticed that in the docs https://keda.sh/docs/2.3/concepts/authentication/#authentication-scopes-namespace-vs-cluster, we can close this indeed. Thanks!

**Comment by tomkerkhove** [comment] 2021-06-17 09:38
@adrianchifor feel free to send a PR on https://github.com/kedacore/keda-docs but this applies to all scalers.

Instead we should maybe link to the conceptual docs instead of scoping to the TA CRD.

**Closed by tomkerkhove** 2021-06-17 09:38 UTC
Labels: bug
