### ISSUE TITLE
KEDA - post 2.11.2 upgrade seeing "couldn't get resource list for external.metrics.k8s.io/v1beta1: the server is currently unable to handle the request" even with dummy-metric

### ISSUE THREAD

**Issue by prashathsenthil** [kedacore/keda#4923] opened 2023-08-30 20:28 UTC
### Report

Hi,

I upgraded KEDA to latest version 2.11.2 on K8S version v1.26.7-eks-2d98532. Post the upgrade along with enabling certManager, everything worked as expected with operator and metric server running just fine for few hours. After that, while performing any kubectl command I could see the below error,

couldn't get resource list for external.metrics.k8s.io/v1beta1: the server is currently unable to handle the request

As suggested here https://github.com/kedacore/keda/issues/4224#issuecomment-1426749781 created dummy workload with cron trigger and even with that in place, still seeing the error message. the apiservice has no errors and no error/failure messages anywhere in the operator and metric server pod logs.

Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.26.7-eks-2d98532

Is there anything else that can be implemented to resolve this error? Please advise.

Thanks!

### Expected Behavior

Running kubectl command should not throw error message "couldn't get resource list for external.metrics.k8s.io/v1beta1: the server is currently unable to handle the request"

This was an issue while running 2.9.3 but after deploying the dummy-metric the error got stopped, but after the upgrade even with dummy-metric this error pops up again

### Actual Behavior

kubectl get scaledobjects -A
E0830 16:27:04.148303   86262 memcache.go:255] couldn't get resource list for external.metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0830 16:27:04.178102   86262 memcache.go:106] couldn't get resource list for external.metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0830 16:27:04.216178   86262 memcache.go:106] couldn't get resource list for external.metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0830 16:27:04.250485   86262 memcache.go:106] couldn't get resource list for external.metrics.k8s.io/v1beta1: the server is currently unable to handle the request
NAMESPACE            NAME                  SCALETARGETKIND      SCALETARGETNAME       MIN   MAX   TRIGGERS   AUTHENTICATION   READY   ACTIVE   FALLBACK   PAUSED    AGE
my-namespace   keda-dummy-workload   apps/v1.Deployment   keda-dummy-workload   0     1     cron                        True    False    Unknown    Unknown   23h

### Steps to Reproduce the Problem

1. Upgrade KEDA from 2.9.3 to 2.11.2 with certManager enabled

### Logs from KEDA operator

```
example
```

### KEDA Version

2.11.2

### Kubernetes Version

1.26

### Platform

Amazon Web Services

**Comment by JorTurFer** [comment] 2023-08-31 17:40
Hi,
v2.11.2 doesn't require the dummy SO because upstream fixed it, and we integrated the fix. I think that there isn any other error here. Could you share KEDA metrics server logs and the APIService as well?

**Comment by tomkerkhove** [comment] 2023-09-01 06:06
Duplicate of https://github.com/kedacore/keda/discussions/4921

**Closed by tomkerkhove** 2023-09-01 06:06 UTC
Labels: bug
