### ISSUE TITLE
[External Scalers] Import all Secrets and metadata from TriggerAuthentication

### ISSUE THREAD

**Issue by Nico385412** [kedacore/keda#5250] opened 2023-12-04 20:35 UTC
### Proposal

Hi everyone 👋 
I would like to propose some changes on the external scaler and would like your advice / authorization before making any pull requests.

As the title says, i would like to change the behaviour on how the elements from TriggerAuthentication are added in requestMetadata.
ATM and according[ to the documentation](https://keda.sh/docs/2.11/scalers/external/#trigger-specification), the only variables we can inject in our slacermetadata payload are :
- caCert
- tlsClientCert
- tlsClientKey

That great but limited. I mean, if you want to implement a custom scaler that can use other kind of authentication this is not possible :(

My proposal is to inject inside the metadata of the slaceObjectRef all the elements (env + secrets) from TriggerAuthentication.

### Use-Case

My use case is the following.
An (very old) external company give us access to a SFTP server and allow us to download files.
There is X files  (👽) (~50Mo each) per server , Y servers to connect, Y credentials that allow us to download one file per server. 

And if a file changes, we must process it as "fast" as possible trough a Job in k8s.
At the moment we have Y Cronjobs triggered *every 30 seconds* to scan the sftp server and if there is any work to do, extract, transform and load to a S3 server.
And most of the time there is nothing to do (10 or 20 changes per day) and we scale job unnecessarily and cost a lot of money.

That why i would like to split this job in 2
- The scan part that I will give to custom scaler 
- The job part that will receive the information of One file change.

And to achieve this goal i tried to: 
- create a TriggerAuthentication that handle sftp credentials for 1 server (from k8s secrets) ✅ 
- create a ScaleJob that use is TriggerAuthentication with the sftp credentials. ✅ 
- Hope Keda to add in the metadata payload the sftp credentials from the triggerAuthentication => 🚫 

So i think it would be great to improve the external scaler to allow the user to inject AuthParams inside the metadata payload.

### Is this a feature you are interested in implementing yourself?

Yes

### Anything else?

My case is for SFTP, but it could be anything else, like : 
- Google drive
- Dynatrace
- Slack
- etc and any specific company cases.

And thank you again for your amazing work <3

**Comment by tomkerkhove** [comment] 2023-12-11 07:04
I think https://github.com/kedacore/keda/issues/2571 is what you are looking for

**Comment by zroubalik** [comment] 2023-12-11 16:27
Shall we close this as a dup?

**Comment by tomkerkhove** [comment] 2023-12-18 10:01
Duplicate of https://github.com/kedacore/keda/issues/2571

**Closed by tomkerkhove** 2023-12-18 10:01 UTC
Labels: needs-discussion, feature-request

**Comment by Nico385412** [comment] 2023-12-22 16:12
indeed it was a duplicate my bad ^^"

**Comment by RSteeno** [comment] 2024-09-19 14:43
@Nico385412, I have the same use case as you outlined here.  Just curious to know how you've solved this.
