### ISSUE TITLE
Fallback oscillates between active and inactive when mixing Value and AverageValue metrics

### ISSUE THREAD

**Issue by RRethy** [kedacore/keda#5514] opened 2024-02-15 19:07 UTC
### Report

When using a ScaledObject with a fallback, 1 metric with type Value, and 1 metric with type AverageValue. If the metrics begin to fail, the Fallback condition on the ScaledObject will switch between `true` and `false` repeatedly.

### Expected Behavior

I would expect it to remain `true` since it is active.

### Actual Behavior

It switches between true and false.

### Steps to Reproduce the Problem

Using this scaledobject with 2 failing metrics of different types and a fallback.

```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  labels:
    app: foo
    scaledobject.keda.sh/name: foo
  name: foo
spec:
  fallback:
    failureThreshold: 3
    replicas: 15
  maxReplicaCount: 50
  minReplicaCount: 10
  pollingInterval: 15
  scaleTargetRef:
    kind: Deployment
    name: foo
  triggers:
    - metadata:
        query: |
          fake_metric{}[1m]
        serverAddress: http://fake.svc.cluster.local:9090
        threshold: "1"
      metricType: AverageValue
      name: trigger1
      type: prometheus
    - metadata:
        query: |
          fake_metric{}[1m]
        serverAddress: http://fake.svc.cluster.local:9090
        threshold: "1"
      metricType: Value
      name: trigger1
      type: prometheus
```

### Logs from KEDA operator

<details>

```
keda-operator 2024-02-15T19:00:01Z	INFO	fallback	Suppressing error, falling back to fallback.replicas	{"scaledObject.Namespace": "foobar", "scaledObject.Name": "foobar", "suppressedError": "Get \"http://foobar.foobar.svc.cluster.local:9090/api/v1/query?query=fake-metric&time=2024-02-15T19:00:01Z\": dial tcp: lookup foobar.foobar.svc.cluster.local on 10.29.248.10:53: no such host", "fallback.replicas": 15}
keda-operator 2024-02-15T19:00:02Z	ERROR	prometheus_scaler	error executing prometheus query	{"type": "ScaledObject", "namespace": "foobar", "name": "foobar", "error": "Get \"http://foobar.foobar.svc.cluster.local:9090/api/v1/query?query=fake-metric&time=2024-02-15T19:00:02Z\": dial tcp: lookup foobar.foobar.svc.cluster.local on 10.29.248.10:53: no such host"}
keda-operator github.com/kedacore/keda/v2/pkg/scalers.(*prometheusScaler).GetMetricsAndActivity
keda-operator 	/workspace/pkg/scalers/prometheus_scaler.go:359
keda-operator github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).GetMetricsAndActivityForScaler
keda-operator 	/workspace/pkg/scaling/cache/scalers_cache.go:129
keda-operator github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).GetScaledObjectMetrics
keda-operator 	/workspace/pkg/scaling/scale_handler.go:508
keda-operator github.com/kedacore/keda/v2/pkg/metricsservice.(*GrpcServer).GetMetrics
keda-operator 	/workspace/pkg/metricsservice/server.go:47
keda-operator github.com/kedacore/keda/v2/pkg/metricsservice/api._MetricsService_GetMetrics_Handler
keda-operator 	/workspace/pkg/metricsservice/api/metrics_grpc.pb.go:99
keda-operator google.golang.org/grpc.(*Server).processUnaryRPC
keda-operator 	/workspace/vendor/google.golang.org/grpc/server.go:1343
keda-operator google.golang.org/grpc.(*Server).handleStream
keda-operator 	/workspace/vendor/google.golang.org/grpc/server.go:1737
keda-operator google.golang.org/grpc.(*Server).serveStreams.func1.1
keda-operator 	/workspace/vendor/google.golang.org/grpc/server.go:986
keda-operator 2024-02-15T19:00:02Z	ERROR	prometheus_scaler	error executing prometheus query	{"type": "ScaledObject", "namespace": "foobar", "name": "foobar", "error": "Get \"http://foobar.foobar.svc.cluster.local:9090/api/v1/query?query=fake-metric&time=2024-02-15T19:00:02Z\": dial tcp: lookup foobar.foobar.svc.cluster.local on 10.29.248.10:53: no such host"}
keda-operator github.com/kedacore/keda/v2/pkg/scalers.(*prometheusScaler).GetMetricsAndActivity
keda-operator 	/workspace/pkg/scalers/prometheus_scaler.go:359
keda-operator github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).GetMetricsAndActivityForScaler
keda-operator 	/workspace/pkg/scaling/cache/scalers_cache.go:139
keda-operator github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).GetScaledObjectMetrics
keda-operator 	/workspace/pkg/scaling/scale_handler.go:508
keda-operator github.com/kedacore/keda/v2/pkg/metricsservice.(*GrpcServer).GetMetrics
keda-operator 	/workspace/pkg/metricsservice/server.go:47
keda-operator github.com/kedacore/keda/v2/pkg/metricsservice/api._MetricsService_GetMetrics_Handler
keda-operator 	/workspace/pkg/metricsservice/api/metrics_grpc.pb.go:99
keda-operator google.golang.org/grpc.(*Server).processUnaryRPC
keda-operator 	/workspace/vendor/google.golang.org/grpc/server.go:1343
keda-operator google.golang.org/grpc.(*Server).handleStream
keda-operator 	/workspace/vendor/google.golang.org/grpc/server.go:1737
keda-operator google.golang.org/grpc.(*Server).serveStreams.func1.1
keda-operator 	/workspace/vendor/google.golang.org/grpc/server.go:986
keda-operator 2024-02-15T19:00:02Z	INFO	fallback	Fallback can only be enabled for triggers with metric of type AverageValue	{"scaledObject.Namespace": "foobar", "scaledObject.Name": "foobar"}
keda-operator 2024-02-15T19:00:02Z	INFO	fallback	Fallback can only be enabled for triggers with metric of type AverageValue	{"scaledObject.Namespace": "foobar", "scaledObject.Name": "foobar"}
keda-operator 2024-02-15T19:00:02Z	ERROR	scale_handler	error getting metric for scaler	{"scaledObject.Namespace": "foobar", "scaledObject.Name": "foobar", "scaler": "trigger2", "error": "Get \"http://foobar.foobar.svc.cluster.local:9090/api/v1/query?query=fake-metric&time=2024-02-15T19:00:02Z\": dial tcp: lookup foobar.foobar.svc.cluster.local on 10.29.248.10:53: no such host"}
keda-operator github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).GetScaledObjectMetrics
keda-operator 	/workspace/pkg/scaling/scale_handler.go:522
keda-operator github.com/kedacore/keda/v2/pkg/metricsservice.(*GrpcServer).GetMetrics
keda-operator 	/workspace/pkg/metricsservice/server.go:47
keda-operator github.com/kedacore/keda/v2/pkg/metricsservice/api._MetricsService_GetMetrics_Handler
keda-operator 	/workspace/pkg/metricsservice/api/metrics_grpc.pb.go:99
keda-operator google.golang.org/grpc.(*Server).processUnaryRPC
keda-operator 	/workspace/vendor/google.golang.org/grpc/server.go:1343
keda-operator google.golang.org/grpc.(*Server).handleStream
keda-operator 	/workspace/vendor/google.golang.org/grpc/server.go:1737
keda-operator google.golang.org/grpc.(*Server).serveStreams.func1.1
keda-operator 	/workspace/vendor/google.golang.org/grpc/server.go:986
keda-operator 2024-02-15T19:00:02Z	INFO	Reconciling ScaledObject	{"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "ScaledObject": {"name":"foobar","namespace":"foobar"}, "namespace": "rrethy-test-keda-production-unrestricted-wbzh", "name": "foobar", "reconcileID": "148c6a96-1c79-453f-816a-67ebfbfdb1bf"}
keda-operator 2024-02-15T19:00:03Z	ERROR	prometheus_scaler	error executing prometheus query	{"type": "ScaledObject", "namespace": "foobar", "name": "foobar", "error": "Get \"http://foobar.foobar.svc.cluster.local:9090/api/v1/query?query=fake-metric&time=2024-02-15T19:00:03Z\": dial tcp: lookup foobar.foobar.svc.cluster.local on 10.29.248.10:53: no such host"}
keda-operator github.com/kedacore/keda/v2/pkg/scalers.(*prometheusScaler).GetMetricsAndActivity
keda-operator 	/workspace/pkg/scalers/prometheus_scaler.go:359
keda-operator github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).GetMetricsAndActivityForScaler
keda-operator 	/workspace/pkg/scaling/cache/scalers_cache.go:129
keda-operator github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScalerState
keda-operator 	/workspace/pkg/scaling/scale_handler.go:699
keda-operator github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScaledObjectState
keda-operator 	/workspace/pkg/scaling/scale_handler.go:590
keda-operator github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
keda-operator 	/workspace/pkg/scaling/scale_handler.go:241
keda-operator github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
keda-operator 	/workspace/pkg/scaling/scale_handler.go:180
keda-operator 2024-02-15T19:00:03Z	ERROR	prometheus_scaler	error executing prometheus query	{"type": "ScaledObject", "namespace": "foobar", "name": "foobar", "error": "Get \"http://foobar.foobar.svc.cluster.local:9090/api/v1/query?query=fake-metric&time=2024-02-15T19:00:03Z\": dial tcp: lookup foobar.foobar.svc.cluster.local on 10.29.248.10:53: no such host"}
keda-operator github.com/kedacore/keda/v2/pkg/scalers.(*prometheusScaler).GetMetricsAndActivity
keda-operator 	/workspace/pkg/scalers/prometheus_scaler.go:359
keda-operator github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).GetMetricsAndActivityForScaler
keda-operator 	/workspace/pkg/scaling/cache/scalers_cache.go:139
keda-operator github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScalerState
keda-operator 	/workspace/pkg/scaling/scale_handler.go:699
keda-operator github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScaledObjectState
keda-operator 	/workspace/pkg/scaling/scale_handler.go:590
keda-operator github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
keda-operator 	/workspace/pkg/scaling/scale_handler.go:241
keda-operator github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
keda-operator 	/workspace/pkg/scaling/scale_handler.go:180
keda-operator 2024-02-15T19:00:03Z	ERROR	scale_handler	error getting scale decision	{"scaledObject.Namespace": "foobar", "scaledObject.Name": "foobar", "scaler": "trigger1", "error": "Get \"http://foobar.foobar.svc.cluster.local:9090/api/v1/query?query=fake-metric&time=2024-02-15T19:00:03Z\": dial tcp: lookup foobar.foobar.svc.cluster.local on 10.29.248.10:53: no such host"}
keda-operator github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScalerState
keda-operator 	/workspace/pkg/scaling/scale_handler.go:720
keda-operator github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScaledObjectState
keda-operator 	/workspace/pkg/scaling/scale_handler.go:590
keda-operator github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
keda-operator 	/workspace/pkg/scaling/scale_handler.go:241
keda-operator github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
keda-operator 	/workspace/pkg/scaling/scale_handler.go:180
```
</details>

### KEDA Version

2.12.1

### Kubernetes Version

1.26

### Platform

Google Cloud

### Scaler Details

Prometheus

### Anything else?

Is it not allowed to mix metric types when using a fallback?

I did not see the HPA scale up and down, the replicas remained at the fallback.

**Comment by JorTurFer** [comment] 2024-02-16 10:05
Hello,
fallback is not supported for other metrics than `AverageValue`:
![image](https://github.com/kedacore/keda/assets/36899226/a3d0ccba-3e32-49da-9ca2-740eace7872b)

I've seen that we aren't validating as part of admission webhook and it's a really good validation to prevent misconfigurations in the future. @kedacore/keda-core-contributors ?

**Comment by zroubalik** [comment] 2024-02-16 10:44
> Hello, fallback is not supported for other metrics than `AverageValue`: ![image](https://private-user-images.githubusercontent.com/36899226/305376898-a3d0ccba-3e32-49da-9ca2-740eace7872b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwODA1NTUsIm5iZiI6MTcwODA4MDI1NSwicGF0aCI6Ii8zNjg5OTIyNi8zMDUzNzY4OTgtYTNkMGNjYmEtM2UzMi00OWRhLTljYTItNzQwZWFjZTc4NzJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDEwNDQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMzNmYzcyZDFmZmFmYmVmNjRmZDliZTQ5NmVjZjhjMzQ5NDdjMDFlOGUyZmNiNjYzNmE2MTU2MWU4Mjg3ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HB8GRT8lkmJE-SoyxPyX_iqD22UAQhU_rDjdGJGne5s)
> 
> I've seen that we aren't validating as part of admission webhook and it's a really good validation to prevent misconfigurations in the future. @kedacore/keda-core-contributors ?

Yes, it is a great candidate fir good-first-issue.

**Comment by JorTurFer** [comment] 2024-02-16 10:59
I've created [this issue](https://github.com/kedacore/keda/issues/5515) to track the admission validation.

Related with the case reporte here, I close this issue as not planned as it's not a bug but design decission

**Closed by JorTurFer** 2024-02-16 10:59 UTC
Labels: bug

**Comment by RRethy** [comment] 2024-02-16 18:49
I understand that fallback isn't supported for `metricType: Value`, but what is an issue is that it breaks the ScaledObject if a user mixes metric types which is an understandable use-case. I had a `metricType: AverageValue` in that configuration which the fallback could replace, from a user's perspective adding another trigger with `metricType: Value` shouldn't break the other trigger.

**Comment by JorTurFer** [comment] 2024-02-17 14:49
Yeah, you're totally right! that's why I've created another specific issue to track the validation of the fallback: https://github.com/kedacore/keda/issues/5515 

From your initial point, I understood (maybe wrongly) that the ScaledObject isn't broken, only the fallback:
> If the metrics begin to fail, the Fallback condition on the ScaledObject will switch between true and false repeatedly.

I mean, if the metrics are available, the scaledobject works, right? If it's not working with available metrics due to the fallback config, definitively it's an issue to track here.
