### ISSUE TITLE
Issue with KEDA autoscaler.

### ISSUE THREAD

**Issue by vipin9387** [kedacore/keda#5171] opened 2023-11-09 10:44 UTC
Sir,
I'm working on using both AMQP and HTTP protocols, but I'm still facing an issue with KEDA autoscaling. Currently, all messages in RabbitMQ are in the ready state, but KEDA only scales up one pod at first and then scales up additional pods after 2 minutes. This delay is causing a problem for me.

_Originally posted by @vipin9387 in https://github.com/kedacore/keda/issues/5119#issuecomment-1797834258_

**Comment by tomkerkhove** [comment] 2023-11-13 08:05
Duplicate of https://github.com/kedacore/keda/issues/5119#issuecomment-1797834258

**Closed by tomkerkhove** 2023-11-13 08:05 UTC
