### ISSUE TITLE
Kafka scaler doesn't scale beyond 100 replicas

### ISSUE THREAD

**Issue by liortct** [kedacore/keda#2888] opened 2022-04-07 09:37 UTC
### Report

According to  [Kafka scaler documention](https://keda.sh/docs/2.6/scalers/apache-kafka/):
![image](https://user-images.githubusercontent.com/38353773/162164268-7758a7b8-1909-4891-b136-e84b1346e3e3.png)
In other words, by default the maximum replicas is the same as the partitions number.
But, if the partitions number is more than 100 the scaler doesn't scale to more than 100 replicas.

### Expected Behavior

If we have a topic with 300 partitions we expected that the maximum replicas number will be 300.

### Actual Behavior

The scaler maximum replicas is 100.

### Steps to Reproduce the Problem

1. Create a Kafka topic with more than 100 partitions, for example 300 partitions 
2. Create deployment that consume messages (with sleep) from the created kafka topic
3. Create a scaledobject with Kafka scaler (don't set the maximum replicas field) 
4. Produce a lot of messages to the created Kafka topic
5. The replicas number will stuck at 100 and don't at 300 as excepted

### Logs from KEDA operator

We can see the problem via the HPA 
![image](https://user-images.githubusercontent.com/38353773/162166487-dfcd0b62-d2c9-4737-8d50-43468461a9aa.png)
You can see that via the target field should be scale up but because the  maximum replicas is 100 we stuck on 100 replicas. 

### KEDA Version

2.6.1

### Kubernetes Version

1.23

### Platform

Any

### Scaler Details

Kafka

### Reason
This bug is happend duo the implementation in [Kafka scaler](https://github.com/kedacore/keda/blob/main/pkg/scalers/kafka_scaler.go) to the maximum scale as the partitions number.
```
if !s.metadata.allowIdleConsumers {
	// don't scale out beyond the number of topicPartitions
	if (totalLag / s.metadata.lagThreshold) > totalTopicPartitions {
		totalLag = totalTopicPartitions * s.metadata.lagThreshold
	}
}
```
This is the mechanism that limit the replicas to the number of partitions. This mechanism actually send "fake" metrics to the HPA in order to don't scale beyond the partitions number.
But, the HPA that created is limit to 100 replicas by default so we can't scale beyond 100 replicas.

### Workaround
I found a workaround for this bug.
You can simply write in the Kafka scaler:
```
maxReplicaCount: 10000
```
In this case we still don't scale beyond the partitions number but will be able to scale up to 10000 in case of topic with 10000 partitions.

**Comment by zroubalik** [comment] 2022-04-07 12:17
100 is the default value for `maxReplicaCount`, so if you don't specify this value, 100 will be used, see the doc: https://keda.sh/docs/2.6/concepts/scaling-deployments/#scaledobject-spec

What prevents you in setting `maxReplicaCount: 300` ?

**Comment by liortct** [comment] 2022-04-07 12:26
> 100 is the default value for `maxReplicaCount`, so if you don't specify this value, 100 will be used, see the doc: https://keda.sh/docs/2.6/concepts/scaling-deployments/#scaledobject-spec
> 
> What prevents you in setting `maxReplicaCount: 300` ?

I can configure the `maxReplicaCount` field. But as document in the Kafka scaler the default `maxReplicaCount` is as the partitions number. This is what I also except, that if I have a topic with 300 partitions by default the `maxReplicaCount` will be 300.

**Comment by zroubalik** [comment] 2022-04-07 12:33
It's clearly written there: https://keda.sh/docs/2.6/scalers/apache-kafka/
> That is, if maxReplicaCount is set more than number of partitions, the scaler won’t scale up to target maxReplicaCount.

But we are definitely open in improving the docs clarity, though this behavior is definitely not a bug.

**Comment by liortct** [comment] 2022-04-07 12:40
> It's clearly written there: https://keda.sh/docs/2.6/scalers/apache-kafka/
> 
> > That is, if maxReplicaCount is set more than number of partitions, the scaler won’t scale up to target maxReplicaCount.
> 
> But we are definitely open in improving the docs clarity, though this behavior is definitely not a bug.

I am not sure that this is not a bug.
In the docs is written that by default `maxReplicaCount = topic partitions number' but its clearly not true.
The real behavior is `maxReplicaCount = min(topic partitions number, 100)'
I will also mention that I think that if I have a topic with 300 partitions I would like that without any configuration (by default) the scaler will scale up to 300 replicas and I would not need to configure `maxReplicaCount: 300` manually.

**Comment by zroubalik** [comment] 2022-04-07 12:43
> In the docs is written that by default `maxReplicaCount = topic partitions number` but its clearly not true.

Could you show me, where is this written?

**Comment by liortct** [comment] 2022-04-07 12:52
> > In the docs is written that by default `maxReplicaCount = topic partitions number` but its clearly not true.
> 
> Could you show me, where is this written?

Ahh ok, I understood.
In the docs is written that `That is, if maxReplicaCount is set more than number of partitions, the scaler won’t scale up to target maxReplicaCount.`, or in other words `maxReplicaCount <= topic partitions number`
But no one say that `maxReplicaCount = topic partitions number`.
This is very tricky. I already open a [PR](https://github.com/kedacore/keda-docs/pull/743) in the docs about it, I will change it a little bit.
This is not a bug this is unclear behavior but I will still say (or ask for feature) that I would like that buy default `maxReplicaCount = topic partitions number`

**Comment by zroubalik** [comment] 2022-04-07 12:56
Cool, I am glad that we understand each other :) If you are going to propose change to the docs, please change it in more versions, not just 2.6, (add please at least 2.5 and 2.7).

**Comment by liortct** [comment] 2022-04-07 13:05
Do you agree that the reasonable behavior is that `maxReplicaCount = topic partitions number`?
As a simple user this is the behavior that I want. If I have a topic with 300 partiontions I want that my deployment will be able to scale to 300 **by default**.
I don't know if to call this issue a bug or feature request but I think this is an issue that should be solved.

**Comment by liortct** [comment] 2022-04-07 13:10
Ok, I will open a feature request for this issue.
Can you approve my [PR](https://github.com/kedacore/keda-docs/pull/743) in the docs about this issue? I think that right now the docs really unclear (my PR solved this issue)

**Comment by rwkarg** [comment] 2022-04-25 15:56
I would find it surprising if the maxReplicaCount defaulted to 100 but that value got ignored and instead allowed 300 replicas. Are there any other triggers that override and allow more replicas than the maxReplicaCount?

If we're looking to have unsurprising behavior, then it feels like clarifying the documentation is the better approach for this one.

**Comment by zroubalik** [comment] 2022-05-03 08:40
There aren't any scalers that exceedes maxReplicaCount. This has been already resolved in the docs.

**Closed by zroubalik** 2022-05-03 08:40 UTC
Labels: bug
