### ISSUE TITLE
gcp-pubsub throwing "could not find stackdriver metric"

### ISSUE THREAD

**Issue by ddlenz** [kedacore/keda#5429] opened 2024-01-23 21:41 UTC
### Report

After updating to 2.13.0, gcp_pub_sub_scaler repeatedly throws "error getting metric" and scale_handler throws "error getting scale decision" with "could not find stackdriver metric with query fetch pubsub_subscription" with unacked messages and failure to scale.

### Expected Behavior

keda scales application from zero

### Actual Behavior

keda fails to scale application from zero

### Steps to Reproduce the Problem

1. create gcp-pubsub scaler
2. publish a message to trigger the scaler
3. check unacked messages and logs

### KEDA Version

2.13.0

### Kubernetes Version

Other

### Platform

Google Cloud

### Scaler Details

gcp pubsub

### Anything else?

kubernetes version 1.28.3-gke.1203001

**Comment by JorTurFer** [comment] 2024-01-24 18:12
Hello,
Does it work on previous versions? Could you share your ScaledObject?

**Comment by FrancoisPoinsot** [comment] 2024-01-30 16:36
I am having the exact same issue.
Same keda version
Kubernetes 1.26
Similar error log.
Also with gcp pubsub scaler.
Can also play the query successfuly in Google Metric Explorer.

I had to rollback to 2.12.1 because we had issue with some workload not scaling up. 
That is what we detected originaly.

**Comment by JorTurFer** [comment] 2024-01-30 22:06
So, does it work in KEDA v2.12.1 and not in KEDA v2.13.0?

**Comment by ekaputra07** [comment] 2024-01-31 05:49
Hi, first of all, thanks for this great project!

But facing same issue here, I'm using:
```
KEDA v2.13.0 / GKE Autopilot / Pub/Sub
```

My ScaledObject:
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: some-name
spec:
  scaleTargetRef:
    name: some-name
  triggers:
    - type: gcp-pubsub
      authenticationRef:
        name: trigger-authentication-dev
        kind: ClusterTriggerAuthentication
      metadata:
        mode: NumUndeliveredMessages
        value: "5"
        activationValue: "0"
        subscriptionName: projects/my-project/subscriptions/my-sub
```

The error:
```bash
2024-01-31T04:53:00Z	ERROR	gcp_pub_sub_scaler	error getting metric	{"type": "ScaledObject", "namespace": "default", "name": "some-name", "metricType": "pubsub.googleapis.com/subscription/num_undelivered_messages", "error": "could not find stackdriver metric with query fetch pubsub_subscription | metric 'pubsub.googleapis.com/subscription/num_undelivered_messages' | filter (resource.project_id == 'my-project' && resource.subscription_id == 'my-sub') | within 1m"}
```
---

I copy-pasted the query I found in error message and run it on GCP's Metrics Explorer:
![iScreen Shoter - 2024013110828997 PM](https://github.com/kedacore/keda/assets/1094221/f018bfd2-f0b0-4692-a4b8-eb7dee3d41e2)

**Things that I noticed are:**
- using `within 1m` the query **sometime** return result, but **most of the time it doesn't**
- using higher time range for example `within 5m` **always** working (return result)

---

Based on its [documentation](https://cloud.google.com/monitoring/api/metrics_gcp#gcp-pubsub), it says:

> **subscription/num_undelivered_messages**
> Number of unacknowledged messages (a.k.a. backlog messages) in a subscription. Sampled every 60 seconds. After sampling, **data is not visible for up to 120 seconds**.

Those might not related, but I'm just trying to provide data as much as possible and hopefully they helps to debug the situation.

---

**And based on the scaler code, looks like we mark it as an Error if stackdriver doesn't return value.**
https://github.com/kedacore/keda/blob/cd57dd9525dc8c25e95a42524701045bb4fdef14/pkg/scalers/gcp/gcp_stackdriver_client.go#L291

**Comment by FrancoisPoinsot** [comment] 2024-01-31 12:36
Some more context about what happened.

I have 8 gcp-pubsub scaledObject.
5 with `minReplicaCount:0` .
3 with `minReplicaCount:1` .

When we upgraded keda to 2.13.0, all 5 deployements targeted by scaledobject with  `minReplicaCount:0`  started to have scaling issue.
They were scaled down to 0. No matter how many pods existed.

Those with `minReplicaCount:1` seems unaffected.
So I am wondering if the problem is specificaly related to the **Activation phase**.

I am trying to get a reproduction scenario. 

here is a basic manifest.
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: test-francois
  namespace: test-francois
spec:
  maxReplicaCount: 5
  minReplicaCount: 0
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-francois
  triggers:
  - authenticationRef:
      kind: ClusterTriggerAuthentication
      name: keda-clustertrigger-auth-gcp-credentials
    metadata:
      mode: SubscriptionSize
      subscriptionName: test-francois-sub
      value: "4"
    type: gcp-pubsub
```

You need to publish manually in the topic in question. Don't need to ack any message. Just use the value to scale up/down any random deployment.

Using this I can reproduce having an error log in keda-operator.
Also I get a steady increase in `keda_scaler_errors` metric.
Also, watching the generated hpa, this is what I see:
```
NAME                     REFERENCE                  TARGETS     MINPODS   MAXPODS   REPLICAS   AGE
keda-hpa-test-francois   Deployment/test-francois   2/4 (avg)   1         5         1          117m
keda-hpa-test-francois   Deployment/test-francois   <unknown>/4 (avg)   1         5         1          117m
```
Roughly 1/3 of the entries show the target with `<unknown>`

However this setup is not enough to reproduce the issue above. The deployement is not being scaled down to 0.
But I wonder if that is just a matter of how frequent those error shows up.

**Comment by FrancoisPoinsot** [comment] 2024-01-31 15:43
here are the goroutines from pprof

[goroutines.txt](https://github.com/kedacore/keda/files/14113806/goroutines.txt)

**Comment by FrancoisPoinsot** [comment] 2024-01-31 16:44
Looking at https://github.com/kedacore/keda/pull/5246/files which as been merged for 2.13.0, I see `GetMetrics` call has been replaced with `QueryMetrics`

https://github.com/kedacore/keda/pull/5246/files#diff-aaa03b99f93c680bd727f6f0a3e9d932c34344ad25b3a254f9a56178c853fe3bR233

And getMetrics query 2 minutes back in time instead of the 1m thatis currently used.
https://github.com/kedacore/keda/blob/cd57dd9525dc8c25e95a42524701045bb4fdef14/pkg/scalers/gcp/gcp_stackdriver_client.go#L219

**Comment by JorTurFer** [comment] 2024-02-01 09:28
Nice research! I was thinking that maybe we changed a default behavior by mistake and it looks like that (and we have to fix it)

I'm thinking on adding the aggregation window as optional parameter too

**Comment by JorTurFer** [comment] 2024-02-01 09:59
@FrancoisPoinsot , I've reverted the change in default time horizon in [this PR](https://github.com/kedacore/keda/pull/5452).

The generated image with that change is `ghcr.io/kedacore/keda-test:pr-5452-c5cf46759c5691b29bb45c6bbb60e3be10cd9f7a`. Would you be willing to test it?

**Comment by FrancoisPoinsot** [comment] 2024-02-01 11:11
I confirm that with `ghcr.io/kedacore/keda-test:pr-5452-c5cf46759c5691b29bb45c6bbb60e3be10cd9f7a` the error log is gone and keda_scaler_errors doesn't show any error.
And the HPA behave as expected.
That looks like a fix.

**Comment by JorTurFer** [comment] 2024-02-01 11:12
Do you see any increase of the goroutines now?

**Comment by JorTurFer** [comment] 2024-02-01 11:15
Thanks for the feedback :heart:

Probably I was right and the issue with the routines was the not closed properly. As now the scaler isn't being regenerated on each check, the issue is mitigated. I've included the proper closing of the connection too as part of the PR: https://github.com/kedacore/keda/pull/5452/commits/4084ee0a73c620567432c1f43b2aacc47cf7c639

**Closed** 2024-02-12 22:20 UTC
Labels: bug

**Comment by JoelDimbernat** [comment] 2024-04-17 17:31
For anyone still encountering this error, ensure that your service account is granted the role `roles/monitoring.viewer` on the project. It's necessary to access `pubsub.googleapis.com/subscription/num_undelivered_messages` and I don't think it's documented anywhere.
