### ISSUE TITLE
Cannot scale a scaledobject to minReplicaCount=0 

### ISSUE THREAD

**Issue by sd2302** [kedacore/keda#903] opened 2020-06-29 18:58 UTC
How can I edit this scaled object to minReplicaCount=0 and maxReplicaCount=0 ?

  Max Replica Count:  0
  Min Replica Count:  0

When I manually edit the scaledobject it immediately changes back 

we need to scale the deployment to replicas 0 for node maintenance 

apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  creationTimestamp: "2020-04-16T22:21:47Z"
  finalizers:
  - finalizer.keda.k8s.io
  generation: 3
  labels:
    app: cloud-ingestionuseractivitysvc
    deploymentName: cloud-ingestionuseractivitysvc
  name: cloud-ingestionuseractivitysvc-scaler
  namespace: cloud
  resourceVersion: "25130625"
  selfLink: /apis/keda.k8s.io/v1alpha1/namespaces/cloud/scaledobjects/cloud-ingestionuseractivitysvc-scaler
  uid: 429390f5-e86c-4bdd-9acf-1ef6b001dbf0
spec:
  maxReplicaCount: 10
  minReplicaCount: 3
  scaleTargetRef:
    deploymentName: cloud-ingestionuseractivitysvc
  triggers:
  - metadata:
      connection: EventBusSettings__ConnectionString
      queueLength: "5"
      subscriptionName: UserActivityIngester
      topicName: eventbus
    type: azure-servicebus
status:
  externalMetricNames:
  - queueLength
  lastActiveTime: "2020-06-29T14:41:44Z"
~

**Comment by tomkerkhove** [comment] 2020-06-30 05:58
Duplicate of https://github.com/kedacore/keda/discussions/902, let's keep the conversation going there maybe?

**Closed** 2020-08-10 09:13 UTC
Labels: bug
