### ISSUE TITLE
Unable to get KEDA working for new version 2.4 and confluent kafka

### ISSUE THREAD

**Issue by harshitak27** [kedacore/keda#2136] opened 2021-10-01 14:52 UTC
### Report

We had been using an older version of KEDA (1.4). We were scaling applications based on Apache Kafka/Confluent Kafka. Now we are looking to upgrade the version of KEDA as our kubernetes cluster is on version 1.20.X.

I had uninstalled the older version and installed the newer version of KEDA and changed our scaled objects and trigger authentications as mentioned here https://keda.sh/docs/2.4/scalers/apache-kafka/

But I am getting the following error

"error": "error getting scaler for trigger #0: error creating kafka client: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"}

With version 1.4, we had a parameter as authMode in trigger authentication (this value was set as "sasl_ssl_plain" in base 64)

With version 2.4, we now have the parameter as sasl. We are setting this value as "plaintext"
Ref: https://github.com/kedacore/keda/blob/main/pkg/scalers/kafka_scaler.go 

I have checked that there are no issues with username and password of confluent kafka as the same values work with version 1.4 without any issues.

### Expected Behavior

Should be able to scale our pods based on the number of messages in confluent kafka. 

### Actual Behavior

"error": "error getting scaler for trigger #0: error creating kafka client: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"}

### Steps to Reproduce the Problem

1.Uninstalled older version of KEDA. We were on KEDA 1.4
2. Installed newer version of KEDA 2.4
3. Made changes to the scaled object
[KafkaScaler.txt](https://github.com/kedacore/keda/files/7268076/KafkaScaler.txt)

4. Checked the HPA and it did not create any HPA
5. Checked the logs of KEDA operator.

### Logs from KEDA operator

"error": "error getting scaler for trigger #0: error creating kafka client: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"}

### KEDA Version

2.4.0

### Kubernetes Version

1.20

### Platform

Microsoft Azure

### Scaler Details

Confluent Kafka

**Comment by tomkerkhove** [comment] 2021-10-01 15:02
Duplicate of #1241

**Closed by tomkerkhove** 2021-10-01 15:02 UTC
Labels: bug
