### ISSUE TITLE
keda-operator v2.13.0 leaks go routines 

### ISSUE THREAD

**Issue by FrancoisPoinsot** [kedacore/keda#5448] opened 2024-01-31 14:28 UTC
### Report

After upgrading keda to 2.13.0 there seems to be a memory leak
Looking at go_goroutines metric I see the number growing indefinitely. Confirmed at least above 30k.
Here is a graph for `go_goroutines`. 
![image](https://github.com/kedacore/keda/assets/25101691/df53192c-d6c6-44c5-aebd-fa2c14cec332)

I have deployed keda in different cloud vendor. I only see this issue in GCP.
Might be related to pubsub scalers I used only in GCP clusters.

### Expected Behavior

memory/goroutine count remains somewhat constant. 
You can see very clearly on the graph above when the upgrade to v2.13.0 happens. 

### Actual Behavior

memory increases indefinitely

### Steps to Reproduce the Problem

1.
2.
3.

### Logs from KEDA operator

```
example
```

### KEDA Version

2.13.0

### Kubernetes Version

1.26

### Platform

Google Cloud

### Scaler Details

prometheus, gcp-pubsub

**Comment by zroubalik** [comment] 2024-01-31 14:32
Thanks for reporting. Could you please check whether you can see the leak also when you use only Prometheus scaler on GCP? So we can narrow down the possible options. Thanks!

**Comment by FrancoisPoinsot** [comment] 2024-01-31 15:21
With only Prometheus scalers, the go routines count is stable at 178 go routines.

**Comment by FrancoisPoinsot** [comment] 2024-01-31 15:44
here are the goroutines from pprof.

[goroutines.txt](https://github.com/kedacore/keda/files/14113825/goroutines.txt)

**Comment by zroubalik** [comment] 2024-01-31 18:37
Cool, thanks for confirmation. And to clarify, this doesn't happen with version < 2.13.0 ? If it is a regression, than we should be able to track down changes in GCP pubu sub scaler.

**Comment by FrancoisPoinsot** [comment] 2024-02-01 08:57
I confirm this does not happen in v2.12.1

**Comment by JorTurFer** [comment] 2024-02-01 09:25
Maybe it's something related with the changes in the gcp client?

**Comment by JorTurFer** [comment] 2024-02-01 10:54
Do you see errors in KEDA operator logs? Maybe we are not closing well the client on failures? Could this be related with https://github.com/kedacore/keda/issues/5429? (as the scaler cache is being refreshed on each error)

**Comment by JorTurFer** [comment] 2024-02-01 11:03
yeah, the new `queryClient` isn't closed, so if the scaler is being refreshed due to #5429, the connections aren't properly closed. I guess that it could be the root cause

**Closed** 2024-02-12 22:20 UTC
Labels: bug
