### ISSUE TITLE
Transfer keda.sh to CNCF

### ISSUE THREAD

**Issue by caniszczyk** [kedacore/keda#671] opened 2020-03-11 19:34 UTC
The domain need needs to be transferred to CNCF for ownership.

We can also setup Netlify DNS to manage DNS, but ownership should be CNCF.

**Comment by tomkerkhove** [comment] 2020-03-11 19:49
Duplicate of https://github.com/kedacore/keda-docs/issues/108

**Closed by tomkerkhove** 2020-03-11 19:49 UTC
Labels: feature-request, needs-discussion
