### ISSUE TITLE
After deleting Keda using command kubectl delete -f keda-2.0.0.yaml, kubernetes cluster goes down.

### ISSUE THREAD

**Issue by fauzankhan007** [kedacore/keda#1447] opened 2020-12-23 09:02 UTC
*A clear and concise description of what the bug is.*

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Logs from KEDA operator

*Provide logs from KEDA operator, if need be.*

```
example
```

## Specifications

  - **KEDA Version:** *Please elaborate*
  - **Platform & Version:** *Please elaborate*
  - **Kubernetes Version:** *Please elaborate*
  - **Scaler(s):** *Please elaborate*

**Comment by tomkerkhove** [comment] 2020-12-23 10:06
Closing as duplicate of https://github.com/kedacore/keda/issues/1448

**Closed by tomkerkhove** 2020-12-23 10:06 UTC
Labels: bug
