### ISSUE TITLE
Log Analytics scaler not taking effect

### ISSUE THREAD

**Issue by sagar027** [kedacore/keda#1632] opened 2021-02-22 20:46 UTC
**Report**

I followed the steps at https://keda.sh/docs/2.1/scalers/azure-log-analytics/  to create a Log Analytics trigger for scaling PODs. I am using the 'Managed Identity' flow for Azure Kubernetes Service (AKS).
All the steps executed fine but when I run the command to get HPA, it seems to be looking for CPU metric instead of the log analytics query result. 

**Expected Behavior**

HPA should show that its been configured with Log Analytics (query) scaler and not CPU metrics.

**Actual Behavior**

Details :
>kubectl get hpa

NAME                                               REFERENCE                    TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
keda-hpa-kedaloganalytics-consumer-scaled-object   Deployment/order-processor   <unknown>/80%   2         10        2          13m

kubectl get hpa
NAME                                               REFERENCE                    TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
keda-hpa-kedaloganalytics-consumer-scaled-object   Deployment/order-processor   <unknown>/80%   2         10        2          107s

>kubectl describe hpa keda-hpa-kedaloganalytics-consumer-scaled-object
Name:                                                  keda-hpa-kedaloganalytics-consumer-scaled-object
Namespace:                                             default
Labels:                                                app.kubernetes.io/managed-by=keda-operator
                                                       app.kubernetes.io/name=keda-hpa-kedaloganalytics-consumer-scaled-object
                                                       app.kubernetes.io/part-of=kedaloganalytics-consumer-scaled-object
                                                       app.kubernetes.io/version=2.1.0
                                                       deploymentName=order-processor
                                                       scaledObjectName=kedaloganalytics-consumer-scaled-object
Annotations:                                           <none>
CreationTimestamp:                                     Tue, 23 Feb 2021 01:40:08 +0530
Reference:                                             Deployment/order-processor
Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  <unknown> / 80%
Min replicas:                                          2
Max replicas:                                          10
Deployment pods:                                       2 current / 0 desired
Conditions:
  Type           Status  Reason                   Message
  ----           ------  ------                   -------
  AbleToScale    True    SucceededGetScale        the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetResourceMetric  the HPA was unable to compute the replica count: missing request for cpu
Events:
  Type     Reason                        Age                 From                       Message
  ----     ------                        ----                ----                       -------
  Warning  FailedGetResourceMetric       15s (x7 over 107s)  horizontal-pod-autoscaler  missing request for cpu
  Warning  FailedComputeMetricsReplicas  15s (x7 over 107s)  horizontal-pod-autoscaler  invalid metrics (1 invalid out of 1), first error is: failed to get cpu utilization: missing request for cpu

order-processor is the name of the deployment which I want to scale.

scaler.yml file:

apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: trigger-auth-kedaloganalytics
spec:
  podIdentity:
    provider: azure
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kedaloganalytics-consumer-scaled-object
  labels:
    deploymentName: order-processor
spec:
  scaleTargetRef:
    kind: Deployment #Optional: Default: Deployment, Available Options: ReplicaSet, Deployment, DaemonSet, StatefulSet
    name: order-processor
  pollingInterval: 30
  cooldownPeriod: 30
  minReplicaCount: 2
  maxReplicaCount: 10
  triggers:
  - type: azure-log-analytics
    metadata:
      workspaceId: "<log-analytics-wks-id>"
      query: |
        Perf
            | where ObjectName == "K8SContainer" and CounterName == "cpuUsageNanoCores"
            | summarize AvgCPUUsageNanoCores = avg(CounterValue) by bin(TimeGenerated, 30m), InstanceName, _ResourceId
            | project AvgCPUUsageNanoCores * 0.0001
            | limit 1 
      threshold: "100"
    authenticationRef:
      name: trigger-auth-kedaloganalytics

**Steps to Reproduce the Problem**

1. Create AKS Cluster with System Managed Identity and with Azure CNI enabled. Attach a log analytics workspace to the AKS cluster from the 'Container Insights' section.
2. Follow the Managed Identity flow for Azure Kubernetes Service (AKS) from here -> https://keda.sh/docs/2.1/scalers/azure-log-analytics/
3. 'Describe' the hpa to notice that its been configured for CPU and not to scale with respects to MetricValue obtained from Log Analytics query. Also, see logs for keda pods.

**Logs from KEDA operator**

>
2021-02-22T20:10:23.659Z        INFO    controller-runtime.metrics      metrics server is starting to listen    {"addr": ":8080"}
2021-02-22T20:10:23.662Z        INFO    controllers.ScaledObject        Running on Kubernetes 1.18      {"version": "v1.18.14"}
2021-02-22T20:10:23.662Z        INFO    setup   Starting manager
2021-02-22T20:10:23.662Z        INFO    setup   KEDA Version: 2.1.0
2021-02-22T20:10:23.662Z        INFO    setup   Git Commit: 4866ce69c4897df532b43390bafe4477275bf65a
2021-02-22T20:10:23.662Z        INFO    setup   Go Version: go1.15.6
2021-02-22T20:10:23.662Z        INFO    setup   Go OS/Arch: linux/amd64
I0222 20:10:23.662780       1 leaderelection.go:243] attempting to acquire leader lease keda/operator.keda.sh...
2021-02-22T20:10:23.663Z        INFO    controller-runtime.manager      starting metrics server {"path": "/metrics"}
I0222 20:10:41.077897       1 leaderelection.go:253] successfully acquired lease keda/operator.keda.sh
2021-02-22T20:10:41.078Z        INFO    controller      Starting EventSource    {"reconcilerGroup": "keda.sh", "reconcilerKind": "ScaledJob", "controller": "scaledjob", "source": "kind source: /, Kind="}
2021-02-22T20:10:41.078Z        INFO    controller      Starting EventSource    {"reconcilerGroup": "keda.sh", "reconcilerKind": "ScaledObject", "controller": "scaledobject", "source": "kind source: /, Kind="}
2021-02-22T20:10:41.178Z        INFO    controller      Starting EventSource    {"reconcilerGroup": "keda.sh", "reconcilerKind": "ScaledObject", "controller": "scaledobject", "source": "kind source: /, Kind="}
2021-02-22T20:10:41.278Z        INFO    controller      Starting Controller     {"reconcilerGroup": "keda.sh", "reconcilerKind": "ScaledJob", "controller": "scaledjob"}
2021-02-22T20:10:41.278Z        INFO    controller      Starting workers        {"reconcilerGroup": "keda.sh", "reconcilerKind": "ScaledJob", "controller": "scaledjob", "worker count": 1}
2021-02-22T20:10:41.278Z        INFO    controller      Starting Controller     {"reconcilerGroup": "keda.sh", "reconcilerKind": "ScaledObject", "controller": "scaledobject"}
2021-02-22T20:10:41.278Z        INFO    controller      Starting workers        {"reconcilerGroup": "keda.sh", "reconcilerKind": "ScaledObject", "controller": "scaledobject", "worker count": 1}
2021-02-22T20:10:41.279Z        INFO    controllers.ScaledObject        Reconciling ScaledObject        {"ScaledObject.Namespace": "default", "ScaledObject.Name": "kedaloganalytics-consumer-scaled-object"}
2021-02-22T20:10:42.194Z        INFO    controllers.ScaledObject        Initializing Scaling logic according to ScaledObject Specification      {"ScaledObject.Namespace": "default", "ScaledObject.Name": "kedaloganalytics-consumer-scaled-object"}
2021-02-22T20:10:42.213Z        INFO    controllers.ScaledObject        Reconciling ScaledObject        {"ScaledObject.Namespace": "default", "ScaledObject.Name": "kedaloganalytics-consumer-scaled-object"}
2021-02-22T20:11:42.833Z        INFO    controllers.ScaledObject        Reconciling ScaledObject        {"ScaledObject.Namespace": "default", "ScaledObject.Name": "kedaloganalytics-consumer-scaled-object"}
2021-02-22T20:11:43.444Z        INFO    controllers.ScaledObject        Initializing Scaling logic according to ScaledObject Specification      {"ScaledObject.Namespace": "default", "ScaledObject.Name": "kedaloganalytics-consumer-scaled-object"}
-----

>kubectl logs keda-operator-metrics-apiserver-
I0222 20:08:17.220503       1 main.go:88] keda_metrics_adapter "msg"="KEDA Version: 2.1.0"
I0222 20:08:17.220554       1 main.go:89] keda_metrics_adapter "msg"="KEDA Commit: 4866ce69c4897df532b43390bafe4477275bf65a"
I0222 20:08:17.220563       1 main.go:90] keda_metrics_adapter "msg"="Go Version: go1.15.6"
I0222 20:08:17.220570       1 main.go:91] keda_metrics_adapter "msg"="Go OS/Arch: linux/amd64"
I0222 20:08:18.872396       1 request.go:655] Throttling request took 1.046702899s, request: GET:https://10.0.0.1:443/apis/rbac.authorization.k8s.io/v1?timeout=32s
I0222 20:08:19.728962       1 provider.go:46] keda_metrics_adapter/provider "msg"="starting"
I0222 20:08:19.728999       1 main.go:149] keda_metrics_adapter "msg"="starting adapter..."
2021-02-22 20:08:19.729005 I | Starting metrics server at :9022
I0222 20:08:22.023720       1 serving.go:325] Generated self-signed cert (apiserver.local.config/certificates/apiserver.crt, apiserver.local.config/certificates/apiserver.key)
I0222 20:08:22.434677       1 secure_serving.go:197] Serving securely on [::]:6443
I0222 20:08:22.434800       1 requestheader_controller.go:169] Starting RequestHeaderAuthRequestController
I0222 20:08:22.434827       1 shared_informer.go:240] Waiting for caches to sync for RequestHeaderAuthRequestController
I0222 20:08:22.434859       1 configmap_cafile_content.go:202] Starting client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I0222 20:08:22.434868       1 shared_informer.go:240] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I0222 20:08:22.434884       1 tlsconfig.go:240] Starting DynamicServingCertificateController
I0222 20:08:22.434912       1 configmap_cafile_content.go:202] Starting client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I0222 20:08:22.434916       1 shared_informer.go:240] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I0222 20:08:22.434859       1 dynamic_serving_content.go:130] Starting serving-cert::apiserver.local.config/certificates/apiserver.crt::apiserver.local.config/certificates/apiserver.key
I0222 20:08:22.534972       1 shared_informer.go:247] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I0222 20:08:22.535005       1 shared_informer.go:247] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I0222 20:08:22.534978       1 shared_informer.go:247] Caches are synced for RequestHeaderAuthRequestController

'kedaloganalytics-consumer-scaled-object' is the ScaledObject crd instance.

**KEDA Version**

2.1.0

**Kubernetes Version**

1.18

**Platform**

Microsoft Azure

**Scaler Details**

Log Analytics scaler

Not sure if I missed something or if there is a bug ?

**Comment by tomkerkhove** [comment] 2021-02-23 07:58
Closing as duplicate of #1629

**Closed by tomkerkhove** 2021-02-23 07:58 UTC
Labels: bug
