### ISSUE TITLE
Possible memory leak in Keda-operator with Kafka scaler

### ISSUE THREAD

**Issue by jeli8-cor** [kedacore/keda#814] opened 2020-05-12 15:57 UTC
Hi everyone,
I started to use keda with the kafka scaler, defined it pretty simple according to the example and after deploying it to production, I noticed that every 3 days the pod reaches the kubernetes limits and get OOM. The memory increasing constantly and I'm not really sure why.
This is the deployment description (I added few parameters such as limits, priorityClass and others):
```
Name:                   keda-operator
Namespace:              keda
CreationTimestamp:      Mon, 27 Apr 2020 12:56:42 +0300
Labels:                 app=keda-operator
                        app.kubernetes.io/component=operator
                        app.kubernetes.io/name=keda-operator
                        app.kubernetes.io/part-of=keda-operator
                        app.kubernetes.io/version=1.4.1
Annotations:            deployment.kubernetes.io/revision: 2
Selector:               app=keda-operator
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app=keda-operator
  Service Account:  keda-operator
  Containers:
   keda-operator:
    Image:      docker.io/kedacore/keda:1.4.1
    Port:       <none>
    Host Port:  <none>
    Command:
      keda
    Args:
      --zap-level=info
    Limits:
      cpu:     100m
      memory:  200Mi
    Requests:
      cpu:     100m
      memory:  200Mi
    Environment:
      WATCH_NAMESPACE:
      POD_NAME:          (v1:metadata.name)
      OPERATOR_NAME:    keda-operator
    Mounts:             <none>
  Volumes:              <none>
  Priority Class Name:  line-of-business-service
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Progressing    True    NewReplicaSetAvailable
  Available      True    MinimumReplicasAvailable
OldReplicaSets:  <none>
NewReplicaSet:   keda-operator-fd678455c (1/1 replicas created)
Events:          <none>
```

The Heap starts at around 30-40M and rinse till almost 200M, jumps to 240 and up and get OOM and restarted by the kubernetes daemon set. 

## Steps to Reproduce the Problem

  1. create a scaledObject to read from a Kafka topic.
  2. After hours of running the memory keeps increasing till it reached the pod limit

## Specifications

  - **KEDA Version:** *1.4.1*
  - **Platform & Version:** *Kafka 2.3.0*
  - **Kubernetes Version:** *1.15*
  - **Scaler(s):** *Kafka*

**Comment by zroubalik** [comment] 2020-05-12 17:00
@jeli8-cor thanks for submitting the issue. Are you willing to help a little bit with tracking donw the bug? Could you please ping me on slack and we can sync?

**Comment by jeli8-cor** [comment] 2020-05-13 04:33
Sure, I would love to help with that. How can I find you in slack?

**Comment by zroubalik** [comment] 2020-05-13 07:29
@jeli8-cor great, you can find me on kubernetes slack, #keda channel

**Comment by jeli8-cor** [comment] 2020-05-13 12:01
Following a few tests and debugs with the dear friend @zroubalik here, I'm updating about the issue:
The issue exists in versions: **1.3.0, 1.4.0, 1.4.1** (these are the ones I checked).
The issue resolved in version **V2** , still in alpha, but currently the pod runs over 3 hours now without even a minor jump in memory. 
The scaler I used was Kafka and I tested it with increasing the lag, increasing the throughput, and "trigger" the scale up and down of the scaler.
According to my checks I test only Kafka scaler and prometheus scaler. Not sure 100%, but I think it's in prometheus scaler too.

**Comment by zroubalik** [comment] 2020-05-13 12:22
@jeli8-cor thanks a lot for the testing!

We should speed up development (and release) of **v2**, in case we are not able to find the cause and proved a fix for this issue in **v1**.

**Comment by zroubalik** [comment] 2020-07-08 15:10
Adding note that this should be included in changelog, so we don't forget.

**Comment by eexwhyzee** [comment] 2020-07-30 21:21
also experienced the same memory leak issues using keda v1.4.1 with the redis list scaler, but I upgraded to v1.5.0 and looks like that resolved it

**Comment by lallinger-arbeit** [comment] 2020-09-21 08:39
@zroubalik Yeah, we have 23 scaledobjects of which 17 use a kafka trigger and 6 a redis trigger

**Comment by mariusgrigoriu** [comment] 2020-12-17 12:35
+1 to CPU and memory usage rising over time. 1000 SO exclusively using the Kafka scaler:

<img width="803" alt="image" src="https://user-images.githubusercontent.com/415231/102488649-3b6c8c00-4021-11eb-93ef-240fde086302.png">

**Comment by MaxWinterstein** [comment] 2021-02-18 11:39
> also experienced the same memory leak issues using keda v1.4.1 with the redis list scaler, but I upgraded to v1.5.0 and looks like that resolved it

Having only redis scalers and running on 2.0 I can confirm it is still existing for me.

![image](https://user-images.githubusercontent.com/5927148/108351793-46d96080-71e6-11eb-9590-174a6328e7ae.png)

Will try 2.1 and if it still is a thing create some own issue on that as is don't see a reference to redis directly in this one.

**Comment by ahmelsayed** [comment] 2021-10-14 23:54
@lallinger-arbeit I think this was the same root cause as https://github.com/kedacore/keda/issues/1565 fixed in https://github.com/kedacore/keda/pull/1572

**Closed by ahmelsayed** 2021-10-14 23:54 UTC
Labels: bug
