### ISSUE TITLE
Provide capability to show multiple triggers in CLI

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda#2047] opened 2021-08-20 08:41 UTC
### Proposal

Provide the capability to show multiple triggers in CLI.

If you create a ScaledObject with multiple triggers today, and run `k get so/<name>` you will have the following output:
```
NAME     SCALETARGETKIND      SCALETARGETNAME   MIN     MAX     TRIGGERS   AUTHENTICATION   READY     ACTIVE    AGE
<name>   apps/v1.Deployment   <target>          1       3       cpu                         True      True      247d
```

However, it would be nice to see all applicable triggers, maybe something like this:
```
NAME     SCALETARGETKIND      SCALETARGETNAME   MIN     MAX     TRIGGERS      AUTHENTICATION   READY     ACTIVE    AGE
<name>   apps/v1.Deployment   <target>          1       3       cpu, memory                         True      True      247d
```

### Use-Case

Improve operational experience and avoid confusion.

**Comment by coderanger** [comment] 2021-08-20 08:53
Technically possible but requires pre-computing the string and storing it in a status field so very slightly annoying :)

**Comment by JorTurFer** [comment] 2021-08-20 19:45
Honestly, I have no idea about how to do this, but I'm open to try to implement it (at least to do my best). This could be a good task to learn more about how Golang and Kubernetes work. Of course, if another wants to do it, I don't have any problem either :)

**Comment by zroubalik** [comment] 2021-08-23 11:12
Duplicate of: https://github.com/kedacore/keda/issues/1943

**Closed by zroubalik** 2021-08-23 11:12 UTC
Labels: needs-discussion, feature-request
