### ISSUE TITLE
The Azure Service Bus metric reports wrong count of Messages in the Queue

### ISSUE THREAD

**Issue by eugen-nw** [kedacore/keda#4515] opened 2023-05-02 19:35 UTC
### Report

I'm running `kubectl describe hpa` to see how thing go. Sometime it reports 0 Messages, which appears to cause the scale-out to not get activated. Sometimes it reports astronomical figures like the one below.  Right now it reports only 2 Messages to be present in the Queue.  For the record, "Service Bus Explorer" reports that there are 16 messages in the Queue.

I have the latest "keda-2.10.2" chart installed.

![image](https://user-images.githubusercontent.com/15199814/235766021-2f160753-eedf-4bf0-9988-08f0c03d04d1.png)

### Expected Behavior

I'd expect to see the accurate count of Messages in the Queue to be reported.

### Actual Behavior

The HPA scales out to only 8 Containers instead of the maximum desired of 10.

### Steps to Reproduce the Problem

I can provide the KEDA deployment & ScaledObject deployment script.

### Logs from KEDA operator

```
example
```

### KEDA Version

2.10.1

### Kubernetes Version

1.25

### Platform

Microsoft Azure

### Scaler Details

HPA

**Comment by JorTurFer** [comment] 2023-05-02 21:14
Hi, 
I think that it's working, and the problem is just a confusion, let me explain what you are seeing.

> Sometimes it reports astronomical figures like the one below

The figure shows `1,5`. This is a common misunderstood and it's because k8s doesn't use float numbers, instead of using floats, k8s changes the scale to `mili` (*1000), that's why you see '1500m' which basically means `1,5` in float numbers.

> Right now it reports only 2 Messages to be present in the Queue. For the record, "Service Bus Explorer" reports that there are 16 messages in the Queue.

In this case, the problem is that the value displayed when you describe the HPA, is the calculated value, not the raw value. As default, metrics are `AverageValue`, so the value that you see when you describe the HPA, is the average value `totalMessages/instances`. In this case, if you see 2 messages describing the HPA and you see 16 messages inside `Service Bus Explorer`, it's because you have 8 instances, so the average value is 2 (16/8=2)

> which appears to cause the scale-out to not get activated

If you allow the scaling to 0 (with `minReplicaCount:0` or `idleReplicaCount:0`), KEDA will scale to 0 the workload if the queue is 0, this is the normal behaviour because the scaler isn't active. If this is a problem, you can increase the `cooldownPeriod` from 300 (seconds) to more, for slowing the scaling to 0 frequency.

As the problem is a misunderstood, I close this issue. If you still think that something isn't working, feel free to repoen the issue again and we can try to figure out what's happening

**Closed by JorTurFer** 2023-05-02 21:14 UTC
Labels: bug

**Comment by eugen-nw** [comment] 2023-05-02 23:50
Thank you for the explanation!

Is there a way to configure KEDA to use the actual count of Messages for scale-out instead of the average?  As I'd used to configure the HPA in the past with:
```
    external:
      metricName: queuemessages
      targetValue: 5
```

As of right now I cannot scale down to 0 Containers because I'm using Windows Containers that are _really_ slow to start up.  For what it's worth, this is how I configure the scale-out at the moment.  My desired behavior is to have 1 Container running all the time and to start scaling out to a max. of 10 for as long as the count of Messages in the Queue stays >= 2.
```
  scaleTargetRef:
    name: aks-aci-boldiq-workforce-gozen-dev
  minReplicaCount: 1
  maxReplicaCount: 10
  pollingInterval: 10
  advanced:
    restoreToOriginalReplicaCount: true
  triggers:
  - type: azure-servicebus
    metadata:
      queueName: gozen-dev-requests
      connectionFromEnv: KEDA_SERVICEBUS_CONNECTIONSTRING_GOZEN_DEV
      messageCount: '2'
```

**Comment by JorTurFer** [comment] 2023-05-03 05:48
Hi
You can use `AverageValue` or `Value`. I think that they aren't exactly how you expect, but `Value` could meet your requirements. You can fin all the information [here](https://keda.sh/docs/2.10/concepts/scaling-deployments/#triggers)
![image](https://user-images.githubusercontent.com/36899226/235840515-d86ab0e0-2bab-4f72-b089-1bc3fce03994.png)

To use `Value` instead of `AvergaeValue`, you just need to change a bit you SO:
```yaml
scaleTargetRef:
    name: aks-aci-boldiq-workforce-gozen-dev
  minReplicaCount: 1
  maxReplicaCount: 10
  pollingInterval: 10
  advanced:
    restoreToOriginalReplicaCount: true
  triggers:
  - type: azure-servicebus
    metricType: Value
    metadata:
      queueName: gozen-dev-requests
      connectionFromEnv: KEDA_SERVICEBUS_CONNECTIONSTRING_GOZEN_DEV
      messageCount: '2'
```

**Comment by eugen-nw** [comment] 2023-05-03 14:41
Thanks very much for the info!  Let me experiment with the `metricType: Value`.  I do not find the documentation to be enlightening.

What I've learned so far wrt `metricType: AverageValue` is that if I set `messageCount: '1'` the scale-out will start as soon as the count of Messages in the Queue exceeds the count of Containers and the count of Containers will always match the count of Messages in the Queue for as long `maxReplicaCount` had not been reached.  If this statement is correct, you may want to include it in the documentation.

**Comment by JorTurFer** [comment] 2023-05-03 15:45
> What I've learned so far wrt metricType: AverageValue is that if I set messageCount: '1' the scale-out will start as soon as the count of Messages in the Queue exceeds the count of Containers and the count of Containers will always match the count of Messages in the Queue for as long maxReplicaCount had not been reached. If this statement is correct, you may want to include it in the documentation.

Isn't this the same? 
> With AverageValue metric type, we can control how many messages, on average, each replica will handle. If our metric is the queue size, the threshold is 5 messages, and the current message count in the queue is 20, HPA will scale the deployment to 20 / 5 = 4 replicas, regardless of the current replica count.

I mean, we explain how the replica count is calculated

**Comment by eugen-nw** [comment] 2023-05-03 22:28
Thanks very much, the `metricType: Value` behaves as I'd expected it to do.  Or like the earlier configuration used to work:
```
external:
      metricName: queuemessages
      targetValue: 5
```

I personally find this mode of operation easier to comprehend.  It may scale out to more Containers on occasion but the extra ones tend to find work to do and as such better handle spikes in Requests.  Again, we're still running Windows Containers that are slow to start up.

**Comment by eugen-nw** [comment] 2023-05-03 22:30
Just out of curiosity, why is scale-out faster these days?  Is it because I set `pollingInterval: 10` or is KEDA or Kubernetes' HPA more responsive?

**Comment by JorTurFer** [comment] 2023-05-03 23:56
> Just out of curiosity, why is scale-out faster these days? Is it because I set pollingInterval: 10 or is KEDA or Kubernetes' HPA more responsive?

What do you mean? If you set `pollingInterval : 10` the operator will check the metric every 10 seconds, but operator works during the activation phase (0-1-0) and I think that you don't work there. During the scaling phase (1-n-1) is the HPA controller who decides when request the metrics (every 15 seconds as default).
If you have super long clusters, maybe you were facing with HPA controller issues because the HPA controller runs in a single thread and depending on your current version, it could be running in multithread approach.
Other option is that you were facing with some performance issue that has been solved during latest releases...
