### ISSUE TITLE
Need Circuit breaker functionality for scaler

### ISSUE THREAD

**Issue by sameerjoshinice** [kedacore/keda#5529] opened 2024-02-23 08:57 UTC
### Proposal

- In case of continuous failures of not getting metadata information from the metric source (eg. Kafka), the scaler should have a circuit breaker to not flood the metric source with multiple requests.
- This could be a configuration which specifies following:

1. The number of failures after which circuit breaker would trigger
2. Duration for which the circuit would remain broken before retry

### Use-Case

We had a use case where Kafka scaler was used to scale the workload based on the topic lag.
However, when the scaler did not have correct permissions for the user it was using, it resulted into many requests being sent to the Kafka. In this case, we had an unfortunate case where AWS MSK went down. One of the reason we got the response is that the user we had used created lot many auth failures for MSK resulting into issue for them.
We 

### Is this a feature you are interested in implementing yourself?

No

**Comment by tomkerkhove** [comment] 2024-02-23 09:13
This is a duplicate of #3949, feel free to join the conversation there

**Closed by tomkerkhove** 2024-02-23 09:13 UTC
Labels: needs-discussion, feature-request
