### ISSUE TITLE
Keda didn't honor "Implicit maintenance-mode deactivation" of HPA

### ISSUE THREAD

**Issue by loicmathieu** [kedacore/keda#2453] opened 2022-01-07 09:31 UTC
### Report

The HPA documentation explains that manually scaling the target to 0 deactivate the HPA, see https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#implicit-maintenance-mode-deactivation.

This is an important feature because it allows maintenance of the application (for example, stoping the consumption of a Kafka topic).

When using Keda, manually scalling to zero a deployment will lead to Keda instantaneously scaling it up to the desired replicas count.

Some mechanism would need to be created for Keda to be able to pause the HPA, using the same mechanism than the HPA one (checking the target desired replica count) or a dedicated Keda mechanism (`enabled` boolean attribute for example).

### Expected Behavior

Manually scalling to 0 a target is honored by Keda.

### Actual Behavior

Manually scalling to 0 a target lead to Keda re-scaling it to the desired replicas count.

### Steps to Reproduce the Problem

1. Create a deployment and a Keda scaler
2. Manually scale the deployment to 0

### Logs from KEDA operator

```
example
```

**Comment by tomkerkhove** [comment] 2022-01-07 09:47
This is by design given KEDA is in the driver seat and manual actions will be ignored.

What you are looking for is most probably https://github.com/kedacore/keda/issues/944

**Comment by zroubalik** [comment] 2022-01-07 10:03
Yeah, that's duplicate of #944

**Closed by zroubalik** 2022-01-07 10:03 UTC
Labels: duplicate, not-a-bug

**Comment by loicmathieu** [comment] 2022-01-07 10:12
I provided feedbacl on #944
