### ISSUE TITLE
Unable to DELETE the keda CRD scaledobjects.keda.sh

### ISSUE THREAD

**Issue by nidiculageorge** [kedacore/keda#4898] opened 2023-08-23 12:07 UTC
### Report

I was trying to uninstall old keda 2.3,0 from cluster but unfortunately, I couldn't delete the following CRD

kubectl delete customresourcedefinition scaledobjects.keda.sh

The below ones are removed

kubectl delete customresourcedefinition clustertriggerauthentications.keda.sh
kubectl delete customresourcedefinition scaledjobs.keda.sh
kubectl delete customresourcedefinition triggerauthentications.keda.sh

Then I ran the below command which ran succsfully

helm uninstall keda -n keda

But when I checked the crds ,I could see scaledobjects.keda.sh in terminating state,and I am unable to install any new keda version in Azure AKS ,when I run the below command

helm install keda kedacore/keda --namespace keda --version 2.10.1 --set nodeSelector."kubernetes.io/os"=linux

I am getting the below error

Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: CustomResourceDefinition "scaledobjects.keda.sh" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "keda"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "keda"

The above error I feel is due to the old scaledojects in the AKS cluster.

Is there a way to remove the unremoved CRD scaledobjects.keda.sh from the AKS cluster

### Expected Behavior

Should be able to delete the crd (scaledobjects.keda.sh) and run the below command successfully in Azure Kubernetes

The above error I feel is due to the old scaledojects in the AKS cluster.

Is there a way to remove the unremoved CRD scaledobjects.keda.sh from the AKS cluster.

### Actual Behavior

kubectl delete customresourcedefinition scaledobjects.keda.sh

The below ones are removed

kubectl delete customresourcedefinition clustertriggerauthentications.keda.sh
kubectl delete customresourcedefinition scaledjobs.keda.sh
kubectl delete customresourcedefinition triggerauthentications.keda.sh

Then I ran the below command which ran succsfully

helm uninstall keda -n keda

But when I checked the crds ,I could see scaledobjects.keda.sh in terminating state,and I am unable to install any new keda version in Azure AKS ,when I run the below command

helm install keda kedacore/keda --namespace keda --version 2.10.1 --set nodeSelector."kubernetes.io/os"=linux

Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: CustomResourceDefinition "scaledobjects.keda.sh" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "keda"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "keda"

The above error I feel is due to the old scaledojects in the AKS cluster.

Is there a way to remove the unremoved CRD scaledobjects.keda.sh from the AKS cluster

### Steps to Reproduce the Problem

1.
2.
3.

### Logs from KEDA operator
The helm uninstall -n keda command removed the keda so no logs ,but the crd scaledobejcts.sh is still there
example
```


### KEDA Version

2.3.0

### Kubernetes Version

1.25

### Platform

Microsoft Azure

### Scaler Details

_No response_

### Anything else?

_No response_

**Comment by JorTurFer** [comment] 2023-08-23 13:09
Hi
Do you still have any resource in that CRD? What do you see if you execute `kubectl get so -A`? If there is any resource you will need to patch them to remove the finalizer, they are blocking the deletion.

Latest versions have the process documented: https://keda.sh/docs/2.11/deploy/#uninstall

**Comment by nidiculageorge** [comment] 2023-08-23 13:13
![image](https://github.com/kedacore/keda/assets/43850474/233e8313-66a9-4a7a-8557-dd5af1b37dfe)


I could see these much resources

@JorTurFer The probelm was I was unable to delete .

kubectl delete customresourcedefinition scaledobjects.keda.sh

**Comment by JorTurFer** [comment] 2023-08-23 13:25
You can't delete the CRD because there are objects using it (all the objects in the picture). When you delete a CRD, k8s tries to delete all the CRs, but ScaledObject has a finalizer, so it's waiting until KEDA removes the finalizer (and KEDA has been removed, so it can't remove the finalizers), that's why you have to delete the finalizers from existing ScaledObjects before deleting the CRD

**Comment by JorTurFer** [comment] 2023-08-23 13:26
BTW, why have you removed KEDA instead of just upgrade it using helm directly? Deleting KEDA you have to remove all the related resources and redeploy them once KEDA is updated. If you just upgrade KEDA using helm, all the ScaledObjects can be there and you don't need to do anymore

**Comment by nidiculageorge** [comment] 2023-08-23 13:31
@JorTurFer thanks for the response...

I removed keda using helm uninstall -n keda command and got removed. But the scaledobject.sh crd is still there we removed without competing removing the scaledobject

as when we tried deleting the crd  kubectl delete customresourcedefinition scaledobjects.keda.sh,it was stuck and we proceeded with the next steps of keda unistall and tired installing the new version with the below command

helm install keda kedacore/keda --namespace keda --version 2.10.1 --set nodeSelector."kubernetes\.io/os"=linux.

As you mentioned we have to remove the finalizers from where do we need to remove the finalizers as we are bit unsure

**Comment by JorTurFer** [comment] 2023-08-23 13:40
If you check any ScaledObject, you will see `metadata.finalizers`, you have to remove them to unlock the ScaledObject, otherwise the ScaledObject is locked until KEDA removes the finalizer. As it's documented in the link I sent, you can remove them programmatically:
```bash
for i in $(kubectl get scaledobjects -A \
  -o jsonpath='{"-n "}{.items[*].metadata.namespace}{" "}{.items[*].kind}{"/"}{.items[*].metadata.name}{"\n"}');
do kubectl patch $i -p '{"metadata":{"finalizers":null}}' --type=merge
done
```
The problem is that until there is at least one ScaledObject in the cluster, you can't delete the CRD. For future updates, I suggest using helm upgrade instead of uninstall/install because helm doesn't allow us to remove the finalicers AFAIK... maybe we can improve the charts using hooks to enforce the CRD deletion before any other stuff 🤔

**Comment by JorTurFer** [comment] 2023-08-23 13:40
> I did a edit of a scaled object and could see finalizer ,do you mean i need to remove those from the scaled objects

yes, that's it

**Comment by nidiculageorge** [comment] 2023-08-23 13:46
@JorTurFer 

When i did an edit it manually opened a notepad,shall i manaully remove all the finalizers from each of the scaled objects,the one that is marked in the screenshot below

![image](https://github.com/kedacore/keda/assets/43850474/7161488d-999b-4cd6-a953-77416a86353f)

**Comment by JorTurFer** [comment] 2023-08-23 13:49
Yes, you can do it and you have to do it for unlocking the ScaledObjects and then, you will be able to delete the CRD

**Comment by nidiculageorge** [comment] 2023-08-23 14:20
Just a query

The command that you gave 

for i in $(kubectl get scaledobjects -A \
  -o jsonpath='{"-n "}{.items[*].metadata.namespace}{" "}{.items[*].kind}{"/"}{.items[*].metadata.name}{"\n"}');
do kubectl patch $i -p '{"metadata":{"finalizers":null}}' --type=merge
done

I am using vscode not sure how to run shall i copy and paste and run

**Comment by JorTurFer** [comment] 2023-08-23 14:22
Yeah, or place it in a bash script, or in the worst case, delete the finalizer manually Xd

**Comment by nidiculageorge** [comment] 2023-08-23 14:32
I am deleting the finalizers manually now the count is reducing when i delete the finalizer and save the scaler..Seems like this was holding on to the keda.scaledobject.sh 

.Hopefullly i can delete the CRD ( kubectl delete customresourcedefinition scaledobjects.keda.sh)  then

**Comment by nidiculageorge** [comment] 2023-08-23 14:45
@JorTurFer 
![image](https://github.com/kedacore/keda/assets/43850474/2f07ae15-13de-40df-aa2e-7ac112dc9f8c)

We have deleted the finalizers proceeding with the below command

kubectl delete customresourcedefinition scaledobjects.keda.sh

**Comment by nidiculageorge** [comment] 2023-08-23 15:00
@JorTurFer  Thanks so much for the support we have succefully deployed the Keda .

Seems like we have to redeploy all the scaledobjects again as we have deleted.

Is there any inplace upgrade of keda using helm we are using the below command to install the keda

helm install keda kedacore/keda --namespace keda --version 2.10.1 --set nodeSelector."kubernetes\.io/os"=linux

**Comment by JorTurFer** [comment] 2023-08-23 15:18
Yes, you can use `helm upgrade --install keda kedacore/keda --namespace keda --version 2.10.1 --set nodeSelector."kubernetes.io/os"=linux` to upgrade the helm release with the version that you want. If you upgrade KEDA using helm, all the ScaledObjects will persist

**Comment by nidiculageorge** [comment] 2023-08-24 02:05
@JorTurFer  Thnaks

If I have to uninstall a particular Keda version say 2.10.1 can i have correct steps on the process how that can be done. The Keda documentation commands where bit confusing previously I had followed the same steps which I mentioned in the issue part based on this github link which I itself raised and the response that I got from Keda .

https://github.com/kedacore/keda/issues/2004

Can I have the correct steps.Say we need to uninstall keda 2.3.0 and Install 2.10.1

**Comment by JorTurFer** [comment] 2023-08-24 06:18
Buen the linked issue is from KEDA 1 to KEDA 2, it's a mejor versio change.
In this case, as is a minor version, just use helm upgrade

**Comment by nidiculageorge** [comment] 2023-08-24 07:50
@JorTurFer  the thing is if we need to unistall a particular keda version from a cluster what all steps are needed.Could you please share that if possible

**Comment by JorTurFer** [comment] 2023-08-24 08:00
> Latest versions have the process documented: [keda.sh/docs/2.11/deploy/#uninstall](https://keda.sh/docs/2.11/deploy/#uninstall)

I sent you in my first message :)

you need to remove KEDA custom resources (SO, SJ,...) and then helm uninstall....

**Comment by JorTurFer** [comment] 2023-08-24 16:46
I guess this is solved, I close it

**Closed by JorTurFer** 2023-08-24 16:46 UTC
Labels: bug

**Comment by nidiculageorge** [comment] 2023-08-30 06:01
PS /home/nithin> helm upgrade --install keda kedacore/keda --namespace keda --version 2.10.1 --set nodeSelector."kubernetes.io/os"=linux

Error: UPGRADE FAILED: failed to create resource: Deployment in version "v1" cannot be handled as a Deployment: json: cannot unmarshal object into Go struct field PodSpec.spec.template.spec.nodeSelector of type string


@JorTurFer  when i try to upgrade I am getting the above error

**Comment by JorTurFer** [comment] 2023-08-30 12:03
Hello,
You don't need to set that selector because it's already added as default because KEDA only works on linux nodes. In your case, the problem is that the selector has to be escaped, but as I said, you can just remove it because it's already set:
![image](https://github.com/kedacore/keda/assets/36899226/76bf14c7-51d3-46af-9ee9-f4df8bbe5bf0)

Try again without the `--set` and let me know how it goes :)

**Comment by nidiculageorge** [comment] 2023-09-02 03:54
![image](https://github.com/kedacore/keda/assets/43850474/2cfc0052-77d4-43d0-809d-064643bcf28e)

@JorTurFer  after the upgrade we can see there are restarts for the keda-admission-webhooks,its not that common ,is this something that we have to be worried about

PS C:\Users\nidicula\OneDrive - RM PLC\WORK\Assessor\AKsSetupPOC\NginxIngressTesting> kubectl logs keda-admission-webhooks-65c5866465-8bt58 -n keda
2023-09-01T11:09:12Z    INFO    controller-runtime.metrics      Metrics server is starting to listen    {"addr": ":8080"}
2023-09-01T11:09:12Z    INFO    setup   Starting admission webhooks
2023-09-01T11:09:12Z    INFO    setup   KEDA Version: 2.10.0
2023-09-01T11:09:12Z    INFO    setup   Git Commit: ee28bf69389bca7bf6d5edd83e2bc3940254114c
2023-09-01T11:09:12Z    INFO    setup   Go Version: go1.19.7
2023-09-01T11:09:12Z    INFO    setup   Go OS/Arch: linux/amd64
2023-09-01T11:09:12Z    INFO    setup   Running on Kubernetes 1.25      {"version": "v1.25.6"}
2023-09-01T11:09:12Z    INFO    controller-runtime.builder      skip registering a mutating webhook, object does not implement admission.Defaulter or WithDefaulter wasn't called       {"GVK": "keda.sh/v1alpha1, Kind=ScaledObject"}
2023-09-01T11:09:12Z    INFO    controller-runtime.builder      Registering a validating webhook        {"GVK": "keda.sh/v1alpha1, Kind=ScaledObject", "path": "/validate-keda-sh-v1alpha1-scaledobject"}
2023-09-01T11:09:12Z    INFO    controller-runtime.webhook      Registering webhook     {"path": "/validate-keda-sh-v1alpha1-scaledobject"}
2023-09-01T11:09:12Z    INFO    controller-runtime.webhook.webhooks     Starting webhook server
2023-09-01T11:09:12Z    INFO    Starting server {"kind": "health probe", "addr": "[::]:8081"}
2023-09-01T11:09:12Z    INFO    Starting server {"path": "/metrics", "kind": "metrics", "addr": "[::]:8080"}
2023-09-01T11:09:12Z    INFO    controller-runtime.certwatcher  Updated current TLS certificate
2023-09-01T11:09:12Z    INFO    controller-runtime.webhook      Serving webhook server  {"host": "", "port": 9443}
2023-09-01T11:09:12Z    INFO    controller-runtime.certwatcher  Starting certificate watcher
PS C:\Users\nidicula\OneDrive - RM PLC\WORK\Assessor\AKsSetupPOC\NginxIngressTesting>

**Comment by JorTurFer** [comment] 2023-09-02 18:22
Definitively, the admission webhook should be restarting. Could you share the logs from the previous container? I'd need also the output of kubetl describe pod

**Comment by nidiculageorge** [comment] 2023-09-04 03:47
@JorTurFer thanks for the prompt reponse.Can you please clarify which previous container.I have done a describe pod of the keda admission webhook will this suffice

PS C:\Users\nidicula\OneDrive - RM PLC\WORK\Assessor\AKsSetupPOC\NginxIngressTesting> kubectl describe pod keda-admission-webhooks-65c5866465-8bt58 -n keda
Name:             keda-admission-webhooks-65c5866465-8bt58
Namespace:        keda
Priority:         0
Service Account:  keda-operator
Node:             aks-linux8core-34370389-vmss0002k2/172.28.199.248
Start Time:       Wed, 30 Aug 2023 17:59:14 +0530
Labels:           app=keda-admission-webhooks
                  app.kubernetes.io/component=operator
                  app.kubernetes.io/instance=keda
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=keda-admission-webhooks
                  app.kubernetes.io/part-of=keda-operator
                  app.kubernetes.io/version=2.10.0
                  helm.sh/chart=keda-2.10.1
                  name=keda-admission-webhooks
                  pod-template-hash=65c5866465
Annotations:      <none>
Status:           Running
IP:               172.28.200.36
IPs:
  IP:           172.28.200.36
Controlled By:  ReplicaSet/keda-admission-webhooks-65c5866465
Containers:
  keda-admission-webhooks:
    Container ID:    containerd://a09c0f99334fb6337854ada76120179758f13550f528bf2ff804dd9fe50ac304
    Image:           ghcr.io/kedacore/keda-admission-webhooks:2.10.0
    Image ID:        ghcr.io/kedacore/keda-admission-webhooks@sha256:8c062db679a95626966f29f9ad26c179acea91105b6258da897b5ed930461267
    Port:            9443/TCP
    Host Port:       0/TCP
    SeccompProfile:  RuntimeDefault
    Command:
      /keda-admission-webhooks
    Args:
      --zap-log-level=info
      --zap-encoder=console
      --zap-time-encoding=rfc3339
      --cert-dir=/certs
    State:          Running
      Started:      Fri, 01 Sep 2023 18:51:08 +0530
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Fri, 01 Sep 2023 18:12:56 +0530
      Finished:     Fri, 01 Sep 2023 18:51:06 +0530
    Ready:          True
    Restart Count:  25
    Limits:
      cpu:     50m
      memory:  100Mi
    Requests:
      cpu:      10m
      memory:   10Mi
    Liveness:   http-get http://:8081/healthz delay=25s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get http://:8081/readyz delay=20s timeout=1s period=10s #success=1 #failure=3
    Environment:
      WATCH_NAMESPACE:
      POD_NAME:         keda-admission-webhooks-65c5866465-8bt58 (v1:metadata.name)
      POD_NAMESPACE:    keda (v1:metadata.namespace)
    Mounts:
      /certs from certificates (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-wtkwh (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  certificates:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kedaorg-certs
    Optional:    false
  kube-api-access-wtkwh:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:                      <none>

**Comment by JorTurFer** [comment] 2023-09-04 06:29
The problem is that you need to assign more resources to the pod. It's restarting due to OOMKill. If you use helm for deploying KEDA, you can use [these values](https://github.com/kedacore/charts/blob/main/keda/values.yaml#L366-L372) to set the resources.

**Comment by nidiculageorge** [comment] 2023-09-04 08:00
@JorTurFer  we have used the following command to upgrade Keda

![image](https://github.com/kedacore/keda/assets/43850474/ac1bd1ab-cfdc-487a-a1e8-164e56e1f025)

Can you please let know how we can pass the values

**Comment by JorTurFer** [comment] 2023-09-04 08:34
Hey,
Sure, as that's helm usage related, you can find all the related information on their docs: https://helm.sh/docs/helm/helm_upgrade/

You have multiple options, overriding them inline, providing your values files, etc

**Comment by nidiculageorge** [comment] 2023-09-14 04:16
@JorTurFer  Just got confused on that part .Can we have the command to set a particular spec to the Keda .Like I need to set a particular spec to the Keda Pod .As the above link is not clear on how we can set a particular spec

**Comment by JorTurFer** [comment] 2023-09-14 10:06
Hi @nidiculageorge 
My previous comment has a link to helm docs about upgrade command. There you can see how you can set values during helm installation:
![image](https://github.com/kedacore/keda/assets/36899226/1f091a5d-1c95-456d-a020-bb5795b83e0d)

The values that you have to update are these: https://github.com/kedacore/charts/blob/main/keda/values.yaml#L348-L372

Sorry but I won't provide the command to you as IMHO it's totally outside KEDA's scope and it's more related with your specific job and use case than with KEDA. I'll help you with any issue related with KEDA, but I won't give you the job already done, sorry
