### ISSUE TITLE
watch all sub folders in azure blob storage scaler?

### ISSUE THREAD

**Issue by nithinkd-geon** [kedacore/keda#1210] opened 2020-10-02 11:22 UTC
is it possible to watch all subfolders in azure blob storage scaler
like can i provide blobPrefix as "RawData/Processing/{containername}" where {containername} is dynamic and need to listen files in and scale accrodingly

**Comment by tomkerkhove** [comment] 2020-12-03 07:13
Adding @jeffhollan @ahmelsayed @anirudhgarg

**Comment by tomkerkhove** [comment] 2021-09-28 06:32
Duplicate of #1789

**Closed by tomkerkhove** 2021-09-28 06:32 UTC
