### ISSUE TITLE
Event Hub Scaler logic is not properly accounting for initial state of empty EventHub partitions

### ISSUE THREAD

**Issue by evillgenius75** [kedacore/keda#830] opened 2020-05-18 18:55 UTC
Numerous test have proven that the KEDA Azure Event Hub scaler on a greenfield Event Hub the scaling mechanism does not handle the `unprocessedEventCountInPartition` correctly and sets the scale metric to a large number which causes the HPA to scale to the maximum.

I believe the issue is with the logic in this function:
https://github.com/kedacore/keda/blob/c2b901b8031c39975fb9ab199304e3986c4e0c31/pkg/scalers/azure_eventhub_scaler.go#L119-L146

Specifically lines 132-142

This issue was also observed by @Christle in https://github.com/kedacore/keda/pull/798#issuecomment-623264756

**Comment by SatishRanjan** [comment] 2020-05-19 22:36
Looking into it.

**Comment by christle** [comment] 2020-05-20 22:42
The reason for that is the initial state of `lastsequencenumber` -1. If there is already a checkpoint inside the storage account, but partitioninfos with `lastsequencenumber` -1 exists, then it runs to line `unprocessedEventCountInPartition = (math.MaxInt64 - partitionInfo.LastSequenceNumber) + checkpoint.SequenceNumber`. This make no sense with -1. And you get a high number. When Messages comes in, the problem is gone. Except in our case where the messages comes over an iot hub into the event hub. Then the `lastsequencenumber`stays on -1 and will not increment. 

But i think, this is easy to solve with a returns 0 on -1.

**Comment by christle** [comment] 2020-05-21 00:24
i will add small fix into the PR #798

**Comment by SatishRanjan** [comment] 2020-05-21 00:52
@christle  - I've a fix for this issue in this PR 
https://github.com/kedacore/keda/pull/848

**Comment by christle** [comment] 2020-05-21 01:42
> @christle - I've a fix for this issue in this PR
> #848

ok, thanks

**Comment by nzthiago** [comment] 2020-06-26 14:31
> > @christle - I've a fix for this issue in this PR
> > #848
> 
> ok, thanks

Should this one be closed?

**Comment by tomkerkhove** [comment] 2020-06-29 05:50
Jup, this should land in v1.5!

**Closed by tomkerkhove** 2020-06-29 05:50 UTC
Labels: integration:azure-functions
