### ISSUE TITLE
Should we return error when  target lost for prometheus scaler

### ISSUE THREAD

**Issue by bamboo12366** [kedacore/keda#3064] opened 2022-05-24 08:56 UTC
### Report

when Prometheus target is lost, the prometheus query will return an empty result here: 
https://github.com/kedacore/keda/blob/main/pkg/scalers/prometheus_scaler.go#L55

The hpa controller will get an 0 value and using the `minReplicas`. Maybe we should return an error when len(reslut) = 0? To let the hpa forget about this workload for a while until the prometheus is back to normal?

There are related issue regarding to this: https://github.com/kedacore/keda/issues/657. But I think we shouldn't patch the replicas when the dependency is not available. Maybe somebody can share more thoughts about that?

### Expected Behavior

keda-metrics return 0 when prometheus is unavailable, hpa controller is patching the `minReplicas` to workload 

### Actual Behavior

keda-metrics should return error when prometheus is unavailable, hpa controller should maintain the same replicas

### Steps to Reproduce the Problem

1. Lost prometheus target

### Logs from KEDA operator

```
example
```

### KEDA Version

2.7.1

### Kubernetes Version

1.20

### Platform

Any

**Comment by zroubalik** [comment] 2022-05-25 11:27
@bamboo12366 is this somehow related to this?

**Comment by bamboo12366** [comment] 2022-05-26 07:30
> @bamboo12366 is this somehow related to #3065?

seems the same thing, can I give a try if no one is working on this?

**Comment by zroubalik** [comment] 2022-05-26 07:45
@bamboo12366 yeah that would be great, let me close this issue and continue on the other one.

Duplicate of #3065

**Closed by zroubalik** 2022-05-26 07:45 UTC
Labels: bug
