### ISSUE TITLE
Added multiple triggers in same scaledobject YAML file but KEDA failed to recognize others except first one in the list

### ISSUE THREAD

**Issue by vinod827** [kedacore/keda#3434] opened 2022-07-27 11:20 UTC
### Report

I tried to add two scalers i.e. CPU and Memory in the triggers attribute in its specification YAML file and deployed the code as well. When I do get on the cluster then it appears like the trigger is enabled only on first one in the list which was **cpu** and not on **memory**. 

This is my code chunk here for a particular scaled object YAML file

```
spec:
  scaleTargetRef:
    name: workload-processor
  cooldownPeriod: 120
  minReplicaCount: 1
  maxReplicaCount: 3
  triggers:
  - type: cpu
    metadata:
      type: AverageValue
      value: "70"
  - type: memory
    metadata:
      type: AverageValue
      value: "70"
```

Here is the output when I do  `kubectl get scaledobject`:-

```
NAME                          SCALETARGETKIND      SCALETARGETNAME   MIN   MAX   TRIGGERS   AUTHENTICATION   READY   ACTIVE   FALLBACK   AGE
workload-processor-keda-scaler   apps/v1.Deployment   workload-processor   1     3     cpu                         True    True     Unknown 
```

There was no problem in deployment. No error were thrown. It appears all good but to no avail. The reason I wrote the both triggers in the same YAML is to remove the code duplication between two files, reduce number of YAML files and also that triggers attribute in YAML is a list, accepting multiple types of scaler.

### Expected Behavior

I was expecting triggers enabled on both CPU and memory.

### Actual Behavior

Trigger was enabled only on first one in the list i.e. **CPU**

### Steps to Reproduce the Problem

Just add multiple scaler types in same ScaledObject YAML file as shown in my sample code and deploy it. Once deployed, then do `kubectl get scaledobject` and refer the Triggers' section in the output, it would show just one trigger type there like below:-

```
NAME                          SCALETARGETKIND      SCALETARGETNAME   MIN   MAX   TRIGGERS   AUTHENTICATION   READY   ACTIVE   FALLBACK   AGE
workload-processor-keda-scaler   apps/v1.Deployment   workload-processor   1     3     cpu                         True    True     Unknown 
```

### Logs from KEDA operator

```
example
```

### KEDA Version

2.6.1

### Kubernetes Version

1.21

### Platform

Amazon Web Services

### Scaler Details

CPU and Memory

**Comment by v-shenoy** [comment] 2022-07-27 11:32
https://github.com/kedacore/keda/issues/1943 

This is the problem.

**Comment by zroubalik** [comment] 2022-07-27 13:03
Yeah, it is just that the cli is not able to display multiple scalers. They are functional and working properly, you can check that with `kubectl get scaledobject -oyaml` or `kubectl describe scaledobject`

**Comment by zroubalik** [comment] 2022-07-27 13:04
Duplicate of #1943

**Closed by zroubalik** 2022-07-27 13:04 UTC
Labels: bug

**Comment by awsservices4** [comment] 2023-03-30 12:39
How to write Mutiple Trigger functions types lik Service Bus,EvnetGrib,EventHub,Http,Timer in a single Scaledobject using KEDA. can we write in a single scaled object, i that correct way to write. if not how to write individual trigger type?
plzz suggest me 
plz give me some examples
