### ISSUE TITLE
The Keda Redis list scale object returns a list length with "m"

### ISSUE THREAD

**Issue by gihanv** [kedacore/keda#4701] opened 2023-06-16 18:46 UTC
### Report

"I am using a KEDA scaleObject for a Redis list Typically, it returns an integer, but occasionally it provides values like '100m' or '245m'. These values with the 'm' suffix seem to represent milli-units. I would like to understand why these values are being returned and how to handle them appropriately in my application.

### Expected Behavior

I expect the average value to be returned as an integer without any appended 'm' suffix.

### Actual Behavior

The HPA is considered successful when the average value is an integer, but it does not trigger when the value includes "m".
![image](https://github.com/kedacore/keda/assets/79891523/31ac6d6e-3db0-4615-a875-68143d758e6e)

### Steps to Reproduce the Problem

1. Run K8s deployment 
2. Create a Keda scale object that refers Redis list (The Redis list must be an active one which consuming data)
-----
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: scaledobject-test-nginx
  namespace: default
spec:
  scaleTargetRef:
    name: test-nginx
  pollingInterval: 5
  cooldownPeriod:  0
  minReplicaCount: 3
  maxReplicaCount: 20
  fallback:
    failureThreshold: 3
    replicas: 6
  advanced:
    restoreToOriginalReplicaCount: false
    horizontalPodAutoscalerConfig: 
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
          selectPolicy: Min
          policies:
          - periodSeconds: 60
            type: Pods
            value: 3
          - periodSeconds: 60
            type: Percent
            value: 10
        scaleUp:
          stabilizationWindowSeconds: 0        
          selectPolicy: Max         
          policies:
          - periodSeconds: 5
            type: Percent
            value: 60
          - periodSeconds: 5
            type: Pods
            value: 3
  triggers:
  - type: redis
    metadata:
      listName: queue-sql
      listLength: "10"
      address: "test.amazonaws.com:6379"

### Logs from KEDA operator

```
There are no issues found in the logs of the Metrics Server and Operator.
---------------------------------------------------------------------------------
2023-06-16T18:41:31Z    INFO    Reconciling ScaledObject        {"controller": "scaledobject", "controllerGroup": "keda.sh", "controllerKind": "ScaledObject", "scaledObject": {"name":"scaledobject-zyde-py","namespace":"test"}, "namespace": "test", "name": "scaledobject-py", "reconcileID": "92524bd8-fbdf-4bd4-9c0b-530fb70ecb18"}
```

### KEDA Version

2.8.2

### Kubernetes Version

1.24

### Platform

Amazon Web Services

### Scaler Details

Redis List

**Comment by JorTurFer** [comment] 2023-06-16 19:34
Hey,
I believe that you will find this discussion interesting: https://github.com/kedacore/keda/discussions/3299
There is explained your questions with some examples

**Comment by JorTurFer** [comment] 2023-06-16 19:38
> ### Expected Behavior
> I expect the average value to be returned as an integer without any appended 'm' suffix.

This isn't possible. If your redis list length is 3, and you have 2 instances, the average value is `1,5`. K8s doesn't manage float numbers and that's why you see `1500m`.

> how to handle them appropriately in my application

You don't need to handle anything, this is something internal between k8s, HPA and KEDA and there isn't any option to change how it's displayed because it's part of the HPA controller design

**Comment by JorTurFer** [comment] 2023-06-16 19:39
I close this issue as it's the normal behavior by design. If after reading the discussion you still have doubts,  please reopen the issue again and we can continue 😄

**Closed by JorTurFer** 2023-06-16 19:39 UTC
Labels: bug
