### ISSUE TITLE
RabbitMQ Message Q based scale up of deployment is not working on Kubernetes version 1.16.8-gke.15 

### ISSUE THREAD

**Issue by nigh8w0lf** [kedacore/keda#895] opened 2020-06-23 05:29 UTC
RabbitMQ Q based scale up of deployment is not working on 1.16.8-gke.15 , It only scales up to one pod and does not scale beyond that, If manually scaled up the scale down seems to be working fine when the Q is empty. 
It seems to be working fine on Kubernetes 1.14.10-gke.36

## Expected Behavior
Should scale up the deployment beyond one pod  and up to the value set for maxReplicaCount when the Q is populated.

## Actual Behavior
Scales up to only one pod no mater how many Items are in the Q

## Steps to Reproduce the Problem

  1. Create a GKE Kubernetes cluster using the regular channel - 1.16.8-gke.15 
  2. helm install keda kedacore/keda -n keda
  3. Follow the Quickstart example here https://github.com/kedacore/sample-go-rabbitmq

## Specifications

  - **KEDA Version: keda-1.4.2 App Version: 1.4.1
  - **Platform & Version: GKE Google Kubernetes engine
  - **Kubernetes Version: 1.16.8-gke.15 
  - **Scaler(s):rabbitmq

**Comment by zroubalik** [comment] 2020-06-25 09:50
Please check logs of KEDA Operator and Metrics Server, to see if there's a problem. My guess would be something about Metrics Server not being functional.

**Comment by zroubalik** [comment] 2020-08-24 08:18
Duplicate of https://github.com/kedacore/keda/issues/515

**Closed by zroubalik** 2020-08-24 08:18 UTC
Labels: bug
