### ISSUE TITLE
HTTP Trigger not scaling up

### ISSUE THREAD

**Issue by rahulpr17** [kedacore/keda#287] opened 2019-07-10 05:10 UTC
I am trying to deploy an HTTP Trigger to keda. I have installed Osiris components for the same. It helped me to scale to zero when no request is coming, but it is not scaling up from 1 instance. I have removed all replica-constraints from deploy.yaml file still no effects. Can you help me with any supportive links?

**Comment by asavaritayal** [comment] 2019-07-11 17:20
@asavaritayal to find the right place for the issue. This looks like an Osiris issue.

**Comment by rahulpr17** [comment] 2019-07-12 04:41
Thanks for looking into the issue. Can you please confirm if it is an issue with Osiris? I have been trying from days to test this and no luck on autoscaling Http Trigger. But Queue trigger is working without any issue.
Also please let us know if Keda support for TimeTrigger will be available in near future?

**Comment by yaron2** [comment] 2019-07-12 04:48
I assume by HTTP Trigger you mean an HTTP Azure Function?

The scale to/from zero you are referring to is only achieved via Osiris, KEDA is not in play here at all, and thus this has to be a (potential) Osiris issue.

You can look for Osiris logs for the different Osiris components under the ```osiris-system``` namespace to help you understand if something went wrong.

**Comment by rahulpr17** [comment] 2019-07-15 05:31
Thank you for the response. I have raised a bug to the osiris team and checking with them.

**Comment by aletc1** [comment] 2019-09-25 21:15
Keda team, please review this:
https://github.com/deislabs/osiris/issues/34?_pjax=%23js-repo-pjax-container#issuecomment-513327042

The issue is with the func toolset that has a missing configuration. e.g if you add this then everything work as expected:

"osiris.deislabs.io/loadBalancerHostname": "locahost"

In my case, localhost was the loadbalancer (Docker Desktop/Kubernetes) but it should be the actual balancer DNS name.

**Comment by tomkerkhove** [comment] 2019-11-26 14:14
I presume this issue can be closed as it's not related to KEDA?

**Closed** 2019-11-26 14:14 UTC
