### ISSUE TITLE
Install fails because v1beta1.external.metrics.k8s.io it's already installed

### ISSUE THREAD

**Issue by ordonezf** [kedacore/keda#2093] opened 2021-09-07 18:16 UTC
### Report

Running `helm install keda kedacore/keda --namespace keda` fails with error

Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: kind: APIService, namespace: , name: v1beta1.external.metrics.k8s.io

### Expected Behavior

`helm install keda kedacore/keda --namespace keda` installs keda on cluster

### Actual Behavior

There is an error because v1beta1.external.metrics.k8s.io already exists in our cluster since it's being installed by the [datadog cluster agent](https://github.com/DataDog/helm-charts/blob/ff98e40b24bb0e8d2eb3bb31d10615dfbaeb1ab9/charts/datadog/templates/agent-apiservice.yaml) 

### Steps to Reproduce the Problem

1. Install datadog cluster agent: https://docs.datadoghq.com/agent/cluster_agent/setup/?tab=helm
2. Try to install keda `helm install keda kedacore/keda --namespace keda`
3. Get an error

### Logs from KEDA operator

```
example
```

### KEDA Version

2.4.0

### Kubernetes Version

1.19

### Platform

Amazon Web Services

### Scaler Details

Postgres

**Comment by JorTurFer** [comment] 2021-09-07 18:43
Could this be related with this other issue? 
https://github.com/kubernetes-sigs/custom-metrics-apiserver/issues/70

**Comment by ordonezf** [comment] 2021-09-07 19:38
I didn't think to look there 😅 
It seems to be the exact same problem. Do you have any idea if sharing the same resource between datadog and keda could be harmful?

**Comment by JorTurFer** [comment] 2021-09-07 20:17
No problem!
Honestly, I haven't got any idea about it but maybe some one comment with extra information

**Comment by zroubalik** [comment] 2021-09-10 07:26
Duplicate of #470

**Comment by zroubalik** [comment] 2021-09-10 07:27
Unfortunately there could be only one instance of `v1beta1.external.metrics.k8s.io` in the cluster 🤷‍♂️

**Closed by zroubalik** 2021-09-10 07:26 UTC
Labels: bug
