### ISSUE TITLE
Define KEDA readiness and liveness probes

### ISSUE THREAD

**Issue by zroubalik** [kedacore/keda#788] opened 2020-04-28 15:40 UTC
KEDA should report it state/availability to the kubernetes cluster.

**Comment by tomkerkhove** [comment] 2020-04-28 18:36
Duplicate of https://github.com/kedacore/keda/issues/237?

**Comment by zroubalik** [comment] 2020-04-29 07:12
@tomkerkhove no, these are probes for the KEDA Operator deployment, to expose KEDA state to the cluster. #237 is talking about probes on the target deployment and scaling based on the probes there.

**Comment by tomkerkhove** [comment] 2020-04-29 07:51
Oh I've missed that, fully agree on this one then!

**Comment by zroubalik** [comment] 2020-05-04 14:02
Fixed in #792

**Comment by tomkerkhove** [comment] 2020-08-17 05:48
Can we get some docs on this on https://keda.sh/docs/2.0/operate/?

**Comment by zroubalik** [comment] 2020-08-19 14:13
I am not sure this is something worth documenting. Those probes exposes state of the Operator and Metrics Server Deployment toward kubernetes, eg. kubernetes scheduler knows when the Deployment is not available and should try to spin another pod.

**Comment by tomkerkhove** [comment] 2020-10-13 14:47
Let's close since it's part of our YAML & chart?

**Closed** 2020-10-13 16:39 UTC
Labels: docs:pending, feature

**Comment by hila3000** [comment] 2021-01-20 11:29
@zroubalik @tomkerkhove Where can I see the Yamls and Chart? I want to see examples of liveness/readiness configuration.

**Comment by tomkerkhove** [comment] 2021-01-20 12:07
Chart can be found here: https://github.com/kedacore/charts/tree/master/keda

**Comment by hila3000** [comment] 2021-01-20 17:13
@tomkerkhove I don't see there an example for scaledobject.yaml.

This is what I have from version 1.5.0. Should it tweaked to be compatible with v2.0.0?

`apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: lf-scaledobject-{{ .Values.tenantId }}
  namespace: {{ .Values.lf_namespace }}
  labels:
    deploymentName: log-forwarding-{{ .Values.tenantId }}
spec:
  scaleTargetRef:
    deploymentName: log-forwarding-{{ .Values.tenantId }}
  pollingInterval: 180
  cooldownPeriod:  43200
  minReplicaCount: 0
  maxReplicaCount: 5
  triggers:
  - type: gcp-pubsub
    metadata:
      subscriptionSize: "50"
      subscriptionName: "lf-data-{{ .Values.tenantId }}-sub"
      credentials: GENERIC_GOOGLE_CREDENTIALS`

**Comment by tomkerkhove** [comment] 2021-01-20 18:15
The probes are for KEDA runtime, ScaledObject scales your workload, so you are in control of those probes.

**Comment by tomkerkhove** [comment] 2021-01-20 18:15
Or maybe I'm not fully getting your question.

**Comment by zroubalik** [comment] 2021-01-20 18:49
You can refer Migration Guide https://keda.sh/docs/2.0/migration/

**Comment by hila3000** [comment] 2021-01-21 10:28
Exactly what I needed :) Thanks!
